/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)

// PAMProviderApiService PAMProviderApi service
type PAMProviderApiService service

// Request for V1 POST /PamProviders
type ApiCreatePamProvidersRequest struct {
	ctx                      context.Context
	ApiService               *PAMProviderApiService
	xKeyfactorRequestedWith  *string
	xKeyfactorApiVersion     *string
	pAMProviderCreateRequest *PAMProviderCreateRequest
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiCreatePamProvidersRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiCreatePamProvidersRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiCreatePamProvidersRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiCreatePamProvidersRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// PAM provider properties to be used
func (r ApiCreatePamProvidersRequest) PAMProviderCreateRequest(pAMProviderCreateRequest PAMProviderCreateRequest) ApiCreatePamProvidersRequest {
	r.pAMProviderCreateRequest = &pAMProviderCreateRequest
	return r
}

// Executes the V1 POST /PamProviders request context
func (r ApiCreatePamProvidersRequest) Execute() (*PAMProviderResponseLegacy, *http.Response, error) {
	return r.ApiService.CreatePamProvidersExecute(r)
}

/*
Creates a new V1 POST /PamProviders request.

# CreatePamProviders Creates a new PAM provider with the associated properties

### PAM Provider Data Types ###
| Value              | Description               |
|--------------------|---------------------------|
| 1                  | string                    |
| 2                  | secret                    |

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreatePamProvidersRequest
*/
func (a *PAMProviderApiService) NewCreatePamProvidersRequest(ctx context.Context) ApiCreatePamProvidersRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiCreatePamProvidersRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,
	}
}

// Executes the API request V1 POST /PamProviders
//
//	@return PAMProviderResponseLegacy
func (a *PAMProviderApiService) CreatePamProvidersExecute(r ApiCreatePamProvidersRequest) (*PAMProviderResponseLegacy, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PAMProviderResponseLegacy
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xKeyfactorRequestedWith == nil {
		return localVarReturnValue, nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json-patch+json", "application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	// body params
	localVarPostBody = r.pAMProviderCreateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// Request for V1 POST /PamProviders/Types
type ApiCreatePamProvidersTypesRequest struct {
	ctx                          context.Context
	ApiService                   *PAMProviderApiService
	xKeyfactorRequestedWith      *string
	xKeyfactorApiVersion         *string
	pAMProviderTypeCreateRequest *PAMProviderTypeCreateRequest
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiCreatePamProvidersTypesRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiCreatePamProvidersTypesRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiCreatePamProvidersTypesRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiCreatePamProvidersTypesRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// PAM provider type properties to be used
func (r ApiCreatePamProvidersTypesRequest) PAMProviderTypeCreateRequest(pAMProviderTypeCreateRequest PAMProviderTypeCreateRequest) ApiCreatePamProvidersTypesRequest {
	r.pAMProviderTypeCreateRequest = &pAMProviderTypeCreateRequest
	return r
}

// Executes the V1 POST /PamProviders/Types request context
func (r ApiCreatePamProvidersTypesRequest) Execute() (*PAMProviderTypeResponse, *http.Response, error) {
	return r.ApiService.CreatePamProvidersTypesExecute(r)
}

/*
Creates a new V1 POST /PamProviders/Types request.

# CreatePamProvidersTypes Creates a new PAM provider type with the associated properties

### PAM Provider Data Types ###
| Value              | Description               |
|--------------------|---------------------------|
| 1                  | string                    |
| 2                  | secret                    |

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreatePamProvidersTypesRequest
*/
func (a *PAMProviderApiService) NewCreatePamProvidersTypesRequest(ctx context.Context) ApiCreatePamProvidersTypesRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiCreatePamProvidersTypesRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,
	}
}

// Executes the API request V1 POST /PamProviders/Types
//
//	@return PAMProviderTypeResponse
func (a *PAMProviderApiService) CreatePamProvidersTypesExecute(r ApiCreatePamProvidersTypesRequest) (*PAMProviderTypeResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PAMProviderTypeResponse
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders/Types"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xKeyfactorRequestedWith == nil {
		return localVarReturnValue, nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json-patch+json", "application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	// body params
	localVarPostBody = r.pAMProviderTypeCreateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// Request for V1 DELETE /PamProviders/{id}
type ApiDeletePamProvidersByIdRequest struct {
	ctx                     context.Context
	ApiService              *PAMProviderApiService
	id                      int32
	xKeyfactorRequestedWith *string
	xKeyfactorApiVersion    *string
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiDeletePamProvidersByIdRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiDeletePamProvidersByIdRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiDeletePamProvidersByIdRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiDeletePamProvidersByIdRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// Executes the V1 DELETE /PamProviders/{id} request context
func (r ApiDeletePamProvidersByIdRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePamProvidersByIdExecute(r)
}

/*
Creates a new V1 DELETE /PamProviders/{id} request.

DeletePamProvidersById Deletes a PAM Provider

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Keyfactor identifier of the PAM provider to be deleted
	@return ApiDeletePamProvidersByIdRequest
*/
func (a *PAMProviderApiService) NewDeletePamProvidersByIdRequest(ctx context.Context, id int32) ApiDeletePamProvidersByIdRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiDeletePamProvidersByIdRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,

		id: id,
	}
}

// Executes the API request
func (a *PAMProviderApiService) DeletePamProvidersByIdExecute(r ApiDeletePamProvidersByIdRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xKeyfactorRequestedWith == nil {
		return nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// Request for V1 DELETE /PamProviders/Types/{id}
type ApiDeletePamProvidersTypesByIdRequest struct {
	ctx                     context.Context
	ApiService              *PAMProviderApiService
	id                      string
	xKeyfactorRequestedWith *string
	xKeyfactorApiVersion    *string
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiDeletePamProvidersTypesByIdRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiDeletePamProvidersTypesByIdRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiDeletePamProvidersTypesByIdRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiDeletePamProvidersTypesByIdRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// Executes the V1 DELETE /PamProviders/Types/{id} request context
func (r ApiDeletePamProvidersTypesByIdRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePamProvidersTypesByIdExecute(r)
}

/*
Creates a new V1 DELETE /PamProviders/Types/{id} request.

DeletePamProvidersTypesById Deletes a PAM provider Type, as long as the PAM type is not currently in use.

### PAM Provider Data Types ###
| Value              | Description               |
|--------------------|---------------------------|
| CyberArk           | string                    |

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id PAM provider type Id to be used
	@return ApiDeletePamProvidersTypesByIdRequest
*/
func (a *PAMProviderApiService) NewDeletePamProvidersTypesByIdRequest(ctx context.Context, id string) ApiDeletePamProvidersTypesByIdRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiDeletePamProvidersTypesByIdRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,

		id: id,
	}
}

// Executes the API request
func (a *PAMProviderApiService) DeletePamProvidersTypesByIdExecute(r ApiDeletePamProvidersTypesByIdRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders/Types/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xKeyfactorRequestedWith == nil {
		return nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

// Request for V1 GET /PamProviders
type ApiGetPamProvidersRequest struct {
	ctx                     context.Context
	ApiService              *PAMProviderApiService
	xKeyfactorRequestedWith *string
	queryString             *string
	pageReturned            *int32
	returnLimit             *int32
	sortField               *string
	sortAscending           *KeyfactorCommonQueryableExtensionsSortOrder
	xKeyfactorApiVersion    *string
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiGetPamProvidersRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiGetPamProvidersRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Contents of the query (ex: field1 -eq value1 AND field2 -gt value2)
func (r ApiGetPamProvidersRequest) QueryString(queryString string) ApiGetPamProvidersRequest {
	r.queryString = &queryString
	return r
}

// The current page within the result set to be returned
func (r ApiGetPamProvidersRequest) PageReturned(pageReturned int32) ApiGetPamProvidersRequest {
	r.pageReturned = &pageReturned
	return r
}

// Maximum number of records to be returned in a single call
func (r ApiGetPamProvidersRequest) ReturnLimit(returnLimit int32) ApiGetPamProvidersRequest {
	r.returnLimit = &returnLimit
	return r
}

// Field by which the results should be sorted (view results via Management Portal for sortable columns)
func (r ApiGetPamProvidersRequest) SortField(sortField string) ApiGetPamProvidersRequest {
	r.sortField = &sortField
	return r
}

// Field sort direction [0&#x3D;ascending, 1&#x3D;descending]
func (r ApiGetPamProvidersRequest) SortAscending(sortAscending KeyfactorCommonQueryableExtensionsSortOrder) ApiGetPamProvidersRequest {
	r.sortAscending = &sortAscending
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiGetPamProvidersRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiGetPamProvidersRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// Executes the V1 GET /PamProviders request context
func (r ApiGetPamProvidersRequest) Execute() ([]PAMProviderResponseLegacy, *http.Response, error) {
	return r.ApiService.GetPamProvidersExecute(r)
}

/*
Creates a new V1 GET /PamProviders request.

# GetPamProviders Returns all PAM providers according to the provided filter and output parameters

### PAM Provider Data Types ###
| Value              | Description               |
|--------------------|---------------------------|
| 1                  | string                    |
| 2                  | secret                    |

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetPamProvidersRequest
*/
func (a *PAMProviderApiService) NewGetPamProvidersRequest(ctx context.Context) ApiGetPamProvidersRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiGetPamProvidersRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,
	}
}

// Executes the API request V1 GET /PamProviders
//
//	@return []PAMProviderResponseLegacy
func (a *PAMProviderApiService) GetPamProvidersExecute(r ApiGetPamProvidersRequest) ([]PAMProviderResponseLegacy, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []PAMProviderResponseLegacy
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xKeyfactorRequestedWith == nil {
		return localVarReturnValue, nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	if r.queryString != nil {
		parameterAddToQuery(localVarQueryParams, "QueryString", r.queryString, "")
	}
	if r.pageReturned != nil {
		parameterAddToQuery(localVarQueryParams, "PageReturned", r.pageReturned, "")
	}
	if r.returnLimit != nil {
		parameterAddToQuery(localVarQueryParams, "ReturnLimit", r.returnLimit, "")
	}
	if r.sortField != nil {
		parameterAddToQuery(localVarQueryParams, "SortField", r.sortField, "")
	}
	if r.sortAscending != nil {
		parameterAddToQuery(localVarQueryParams, "SortAscending", r.sortAscending, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// Request for V1 GET /PamProviders/{id}
type ApiGetPamProvidersByIdRequest struct {
	ctx                     context.Context
	ApiService              *PAMProviderApiService
	id                      int32
	xKeyfactorRequestedWith *string
	xKeyfactorApiVersion    *string
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiGetPamProvidersByIdRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiGetPamProvidersByIdRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiGetPamProvidersByIdRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiGetPamProvidersByIdRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// Executes the V1 GET /PamProviders/{id} request context
func (r ApiGetPamProvidersByIdRequest) Execute() (*PAMProviderResponseLegacy, *http.Response, error) {
	return r.ApiService.GetPamProvidersByIdExecute(r)
}

/*
Creates a new V1 GET /PamProviders/{id} request.

# GetPamProvidersById Returns a single PAM Provider that matches the associated id

### PAM Provider Data Types ###
| Value              | Description               |
|--------------------|---------------------------|
| 1                  | string                    |
| 2                  | secret                    |

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Keyfactor identifier of the PAM provider
	@return ApiGetPamProvidersByIdRequest
*/
func (a *PAMProviderApiService) NewGetPamProvidersByIdRequest(ctx context.Context, id int32) ApiGetPamProvidersByIdRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiGetPamProvidersByIdRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,

		id: id,
	}
}

// Executes the API request V1 GET /PamProviders/{id}
//
//	@return PAMProviderResponseLegacy
func (a *PAMProviderApiService) GetPamProvidersByIdExecute(r ApiGetPamProvidersByIdRequest) (*PAMProviderResponseLegacy, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PAMProviderResponseLegacy
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.id < 0 {
		return localVarReturnValue, nil, reportError("id must be greater than 0")
	}
	if r.id > 2147483647 {
		return localVarReturnValue, nil, reportError("id must be less than 2147483647")
	}
	if r.xKeyfactorRequestedWith == nil {
		return localVarReturnValue, nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// Request for V1 GET /PamProviders/Types
type ApiGetPamProvidersTypesRequest struct {
	ctx                     context.Context
	ApiService              *PAMProviderApiService
	xKeyfactorRequestedWith *string
	xKeyfactorApiVersion    *string
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiGetPamProvidersTypesRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiGetPamProvidersTypesRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiGetPamProvidersTypesRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiGetPamProvidersTypesRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// Executes the V1 GET /PamProviders/Types request context
func (r ApiGetPamProvidersTypesRequest) Execute() ([]PAMProviderTypeResponse, *http.Response, error) {
	return r.ApiService.GetPamProvidersTypesExecute(r)
}

/*
Creates a new V1 GET /PamProviders/Types request.

# GetPamProvidersTypes Returns all PAM provider types in the Keyfactor instance

### PAM Provider Data Types ###
| Value              | Description               |
|--------------------|---------------------------|
| 1                  | string                    |
| 2                  | secret                    |

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetPamProvidersTypesRequest
*/
func (a *PAMProviderApiService) NewGetPamProvidersTypesRequest(ctx context.Context) ApiGetPamProvidersTypesRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiGetPamProvidersTypesRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,
	}
}

// Executes the API request V1 GET /PamProviders/Types
//
//	@return []PAMProviderTypeResponse
func (a *PAMProviderApiService) GetPamProvidersTypesExecute(r ApiGetPamProvidersTypesRequest) ([]PAMProviderTypeResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []PAMProviderTypeResponse
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders/Types"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xKeyfactorRequestedWith == nil {
		return localVarReturnValue, nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

// Request for V1 PUT /PamProviders
type ApiUpdatePamProvidersRequest struct {
	ctx                            context.Context
	ApiService                     *PAMProviderApiService
	xKeyfactorRequestedWith        *string
	xKeyfactorApiVersion           *string
	pAMProviderUpdateRequestLegacy *PAMProviderUpdateRequestLegacy
}

// Type of the request [XMLHttpRequest, APIClient]
func (r ApiUpdatePamProvidersRequest) XKeyfactorRequestedWith(xKeyfactorRequestedWith string) ApiUpdatePamProvidersRequest {
	r.xKeyfactorRequestedWith = &xKeyfactorRequestedWith
	return r
}

// Desired version of the api, if not provided defaults to v1
func (r ApiUpdatePamProvidersRequest) XKeyfactorApiVersion(xKeyfactorApiVersion string) ApiUpdatePamProvidersRequest {
	r.xKeyfactorApiVersion = &xKeyfactorApiVersion
	return r
}

// PAM provider properties to be used
func (r ApiUpdatePamProvidersRequest) PAMProviderUpdateRequestLegacy(pAMProviderUpdateRequestLegacy PAMProviderUpdateRequestLegacy) ApiUpdatePamProvidersRequest {
	r.pAMProviderUpdateRequestLegacy = &pAMProviderUpdateRequestLegacy
	return r
}

// Executes the V1 PUT /PamProviders request context
func (r ApiUpdatePamProvidersRequest) Execute() (*PAMProviderResponseLegacy, *http.Response, error) {
	return r.ApiService.UpdatePamProvidersExecute(r)
}

/*
Creates a new V1 PUT /PamProviders request.

# UpdatePamProviders Updates an existing PAM provider according to the provided properties

### PAM Provider Data Types ###
| Value              | Description               |
|--------------------|---------------------------|
| 1                  | string                    |
| 2                  | secret                    |

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiUpdatePamProvidersRequest
*/
func (a *PAMProviderApiService) NewUpdatePamProvidersRequest(ctx context.Context) ApiUpdatePamProvidersRequest {

	requestedWith := "APIClient"
	apiVersion := "1"

	return ApiUpdatePamProvidersRequest{
		ApiService:              a,
		ctx:                     ctx,
		xKeyfactorRequestedWith: &requestedWith,
		xKeyfactorApiVersion:    &apiVersion,
	}
}

// Executes the API request V1 PUT /PamProviders
//
//	@return PAMProviderResponseLegacy
func (a *PAMProviderApiService) UpdatePamProvidersExecute(r ApiUpdatePamProvidersRequest) (*PAMProviderResponseLegacy, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PAMProviderResponseLegacy
	)

	apiBasePath := a.client.AuthClient.GetServerConfig().APIPath
	if apiBasePath == "" {
		apiBasePath = "/KeyfactorAPI"
	}

	if r.xKeyfactorRequestedWith == nil {
		requestedWith := "APIClient"
		r.xKeyfactorRequestedWith = &requestedWith
	}

	if r.xKeyfactorApiVersion == nil {
		apiVersion := "1"
		r.xKeyfactorApiVersion = &apiVersion
	}

	localVarPath := apiBasePath + "/PamProviders"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xKeyfactorRequestedWith == nil {
		return localVarReturnValue, nil, reportError("xKeyfactorRequestedWith is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json-patch+json", "application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToQuery(localVarHeaderParams, "x-keyfactor-requested-with", r.xKeyfactorRequestedWith, "")
	if r.xKeyfactorApiVersion != nil {
		parameterAddToQuery(localVarHeaderParams, "x-keyfactor-api-version", r.xKeyfactorApiVersion, "")
	}
	// body params
	localVarPostBody = r.pAMProviderUpdateRequestLegacy
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
