/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the SecurityLegacySecurityRolesSecurityRoleUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityLegacySecurityRolesSecurityRoleUpdateRequest{}

// SecurityLegacySecurityRolesSecurityRoleUpdateRequest struct for SecurityLegacySecurityRolesSecurityRoleUpdateRequest
type SecurityLegacySecurityRolesSecurityRoleUpdateRequest struct {
	// The Id of the security role to update
	Id int32 `json:"Id"`
	// The name of the security role to update
	Name string `json:"Name"`
	// The description to be used on the updated security role
	Description string `json:"Description"`
	// The email address to be used on the updated security role
	EmailAddress NullableString `json:"EmailAddress,omitempty"`
	// Whether or not the security role should be enabled
	Enabled *bool `json:"Enabled,omitempty"`
	// Whether or not the security role should be private
	Private *bool `json:"Private,omitempty"`
	// The permissions to include in the role. These must be supplied in the format \"Area:Permission\"
	Permissions []string `json:"Permissions,omitempty"`
	// The Id of the permission set the role belongs to.
	PermissionSetId *string `json:"PermissionSetId,omitempty"`
	// The Keyfactor identities to assign to the updated role
	Identities []CSSCMSDataModelModelsSecurityIdentitiesSecurityIdentityIdentifier `json:"Identities,omitempty"`
}

// NewSecurityLegacySecurityRolesSecurityRoleUpdateRequest instantiates a new SecurityLegacySecurityRolesSecurityRoleUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityLegacySecurityRolesSecurityRoleUpdateRequest(id int32, name string, description string) *SecurityLegacySecurityRolesSecurityRoleUpdateRequest {
	this := SecurityLegacySecurityRolesSecurityRoleUpdateRequest{}
	this.Id = id
	this.Name = name
	this.Description = description
	return &this
}

// NewSecurityLegacySecurityRolesSecurityRoleUpdateRequestWithDefaults instantiates a new SecurityLegacySecurityRolesSecurityRoleUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityLegacySecurityRolesSecurityRoleUpdateRequestWithDefaults() *SecurityLegacySecurityRolesSecurityRoleUpdateRequest {
	this := SecurityLegacySecurityRolesSecurityRoleUpdateRequest{}
	return &this
}

// GetId returns the Id field value
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetDescription(v string) {
	o.Description = v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetEmailAddress() string {
	if o == nil || isNil(o.EmailAddress.Get()) {
		var ret string
		return ret
	}
	return *o.EmailAddress.Get()
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetEmailAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailAddress.Get(), o.EmailAddress.IsSet()
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) HasEmailAddress() bool {
	if o != nil && o.EmailAddress.IsSet() {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given NullableString and assigns it to the EmailAddress field.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetEmailAddress(v string) {
	o.EmailAddress.Set(&v)
}

// SetEmailAddressNil sets the value for EmailAddress to be an explicit nil
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetEmailAddressNil() {
	o.EmailAddress.Set(nil)
}

// UnsetEmailAddress ensures that no value is present for EmailAddress, not even an explicit nil
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) UnsetEmailAddress() {
	o.EmailAddress.Unset()
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetEnabled() bool {
	if o == nil || isNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) HasEnabled() bool {
	if o != nil && !isNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetPrivate() bool {
	if o == nil || isNil(o.Private) {
		var ret bool
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetPrivateOk() (*bool, bool) {
	if o == nil || isNil(o.Private) {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) HasPrivate() bool {
	if o != nil && !isNil(o.Private) {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given bool and assigns it to the Private field.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetPrivate(v bool) {
	o.Private = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetPermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetPermissionsOk() ([]string, bool) {
	if o == nil || isNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) HasPermissions() bool {
	if o != nil && isNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetPermissions(v []string) {
	o.Permissions = v
}

// GetPermissionSetId returns the PermissionSetId field value if set, zero value otherwise.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetPermissionSetId() string {
	if o == nil || isNil(o.PermissionSetId) {
		var ret string
		return ret
	}
	return *o.PermissionSetId
}

// GetPermissionSetIdOk returns a tuple with the PermissionSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetPermissionSetIdOk() (*string, bool) {
	if o == nil || isNil(o.PermissionSetId) {
		return nil, false
	}
	return o.PermissionSetId, true
}

// HasPermissionSetId returns a boolean if a field has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) HasPermissionSetId() bool {
	if o != nil && !isNil(o.PermissionSetId) {
		return true
	}

	return false
}

// SetPermissionSetId gets a reference to the given string and assigns it to the PermissionSetId field.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetPermissionSetId(v string) {
	o.PermissionSetId = &v
}

// GetIdentities returns the Identities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetIdentities() []CSSCMSDataModelModelsSecurityIdentitiesSecurityIdentityIdentifier {
	if o == nil {
		var ret []CSSCMSDataModelModelsSecurityIdentitiesSecurityIdentityIdentifier
		return ret
	}
	return o.Identities
}

// GetIdentitiesOk returns a tuple with the Identities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) GetIdentitiesOk() ([]CSSCMSDataModelModelsSecurityIdentitiesSecurityIdentityIdentifier, bool) {
	if o == nil || isNil(o.Identities) {
		return nil, false
	}
	return o.Identities, true
}

// HasIdentities returns a boolean if a field has been set.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) HasIdentities() bool {
	if o != nil && isNil(o.Identities) {
		return true
	}

	return false
}

// SetIdentities gets a reference to the given []CSSCMSDataModelModelsSecurityIdentitiesSecurityIdentityIdentifier and assigns it to the Identities field.
func (o *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) SetIdentities(v []CSSCMSDataModelModelsSecurityIdentitiesSecurityIdentityIdentifier) {
	o.Identities = v
}

func (o SecurityLegacySecurityRolesSecurityRoleUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityLegacySecurityRolesSecurityRoleUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Id"] = o.Id
	toSerialize["Name"] = o.Name
	toSerialize["Description"] = o.Description
	if o.EmailAddress.IsSet() {
		toSerialize["EmailAddress"] = o.EmailAddress.Get()
	}
	if !isNil(o.Enabled) {
		toSerialize["Enabled"] = o.Enabled
	}
	if !isNil(o.Private) {
		toSerialize["Private"] = o.Private
	}
	if o.Permissions != nil {
		toSerialize["Permissions"] = o.Permissions
	}
	if !isNil(o.PermissionSetId) {
		toSerialize["PermissionSetId"] = o.PermissionSetId
	}
	if o.Identities != nil {
		toSerialize["Identities"] = o.Identities
	}
	return toSerialize, nil
}

type NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest struct {
	value *SecurityLegacySecurityRolesSecurityRoleUpdateRequest
	isSet bool
}

func (v NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest) Get() *SecurityLegacySecurityRolesSecurityRoleUpdateRequest {
	return v.value
}

func (v *NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest) Set(val *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest(val *SecurityLegacySecurityRolesSecurityRoleUpdateRequest) *NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest {
	return &NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest{value: val, isSet: true}
}

func (v NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityLegacySecurityRolesSecurityRoleUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
