/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CertificateStoresTypesStoreTypeProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateStoresTypesStoreTypeProperty{}

// CertificateStoresTypesStoreTypeProperty struct for CertificateStoresTypesStoreTypeProperty
type CertificateStoresTypesStoreTypeProperty struct {
	Id                *int32                                             `json:"Id,omitempty"`
	StoreTypeId       *int32                                             `json:"StoreTypeId,omitempty"`
	Name              NullableString                                     `json:"Name,omitempty"`
	DisplayName       NullableString                                     `json:"DisplayName,omitempty"`
	Type              *CSSCMSCoreEnumsCertificateStoreTypePropertyType   `json:"Type,omitempty"`
	DependsOn         NullableString                                     `json:"DependsOn,omitempty"`
	DefaultValue      NullableString                                     `json:"DefaultValue,omitempty"`
	Required          NullableBool                                       `json:"Required,omitempty"`
	ValidationOptions *CertificateStoresTypesPropertiesValidationOptions `json:"ValidationOptions,omitempty"`
}

// NewCertificateStoresTypesStoreTypeProperty instantiates a new CertificateStoresTypesStoreTypeProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateStoresTypesStoreTypeProperty() *CertificateStoresTypesStoreTypeProperty {
	this := CertificateStoresTypesStoreTypeProperty{}
	return &this
}

// NewCertificateStoresTypesStoreTypePropertyWithDefaults instantiates a new CertificateStoresTypesStoreTypeProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateStoresTypesStoreTypePropertyWithDefaults() *CertificateStoresTypesStoreTypeProperty {
	this := CertificateStoresTypesStoreTypeProperty{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CertificateStoresTypesStoreTypeProperty) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesStoreTypeProperty) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CertificateStoresTypesStoreTypeProperty) SetId(v int32) {
	o.Id = &v
}

// GetStoreTypeId returns the StoreTypeId field value if set, zero value otherwise.
func (o *CertificateStoresTypesStoreTypeProperty) GetStoreTypeId() int32 {
	if o == nil || isNil(o.StoreTypeId) {
		var ret int32
		return ret
	}
	return *o.StoreTypeId
}

// GetStoreTypeIdOk returns a tuple with the StoreTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesStoreTypeProperty) GetStoreTypeIdOk() (*int32, bool) {
	if o == nil || isNil(o.StoreTypeId) {
		return nil, false
	}
	return o.StoreTypeId, true
}

// HasStoreTypeId returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasStoreTypeId() bool {
	if o != nil && !isNil(o.StoreTypeId) {
		return true
	}

	return false
}

// SetStoreTypeId gets a reference to the given int32 and assigns it to the StoreTypeId field.
func (o *CertificateStoresTypesStoreTypeProperty) SetStoreTypeId(v int32) {
	o.StoreTypeId = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificateStoresTypesStoreTypeProperty) GetName() string {
	if o == nil || isNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificateStoresTypesStoreTypeProperty) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CertificateStoresTypesStoreTypeProperty) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) UnsetName() {
	o.Name.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificateStoresTypesStoreTypeProperty) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificateStoresTypesStoreTypeProperty) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *CertificateStoresTypesStoreTypeProperty) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CertificateStoresTypesStoreTypeProperty) GetType() CSSCMSCoreEnumsCertificateStoreTypePropertyType {
	if o == nil || isNil(o.Type) {
		var ret CSSCMSCoreEnumsCertificateStoreTypePropertyType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesStoreTypeProperty) GetTypeOk() (*CSSCMSCoreEnumsCertificateStoreTypePropertyType, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given CSSCMSCoreEnumsCertificateStoreTypePropertyType and assigns it to the Type field.
func (o *CertificateStoresTypesStoreTypeProperty) SetType(v CSSCMSCoreEnumsCertificateStoreTypePropertyType) {
	o.Type = &v
}

// GetDependsOn returns the DependsOn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificateStoresTypesStoreTypeProperty) GetDependsOn() string {
	if o == nil || isNil(o.DependsOn.Get()) {
		var ret string
		return ret
	}
	return *o.DependsOn.Get()
}

// GetDependsOnOk returns a tuple with the DependsOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificateStoresTypesStoreTypeProperty) GetDependsOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DependsOn.Get(), o.DependsOn.IsSet()
}

// HasDependsOn returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasDependsOn() bool {
	if o != nil && o.DependsOn.IsSet() {
		return true
	}

	return false
}

// SetDependsOn gets a reference to the given NullableString and assigns it to the DependsOn field.
func (o *CertificateStoresTypesStoreTypeProperty) SetDependsOn(v string) {
	o.DependsOn.Set(&v)
}

// SetDependsOnNil sets the value for DependsOn to be an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) SetDependsOnNil() {
	o.DependsOn.Set(nil)
}

// UnsetDependsOn ensures that no value is present for DependsOn, not even an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) UnsetDependsOn() {
	o.DependsOn.Unset()
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificateStoresTypesStoreTypeProperty) GetDefaultValue() string {
	if o == nil || isNil(o.DefaultValue.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultValue.Get()
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificateStoresTypesStoreTypeProperty) GetDefaultValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultValue.Get(), o.DefaultValue.IsSet()
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasDefaultValue() bool {
	if o != nil && o.DefaultValue.IsSet() {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given NullableString and assigns it to the DefaultValue field.
func (o *CertificateStoresTypesStoreTypeProperty) SetDefaultValue(v string) {
	o.DefaultValue.Set(&v)
}

// SetDefaultValueNil sets the value for DefaultValue to be an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) SetDefaultValueNil() {
	o.DefaultValue.Set(nil)
}

// UnsetDefaultValue ensures that no value is present for DefaultValue, not even an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) UnsetDefaultValue() {
	o.DefaultValue.Unset()
}

// GetRequired returns the Required field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificateStoresTypesStoreTypeProperty) GetRequired() bool {
	if o == nil || isNil(o.Required.Get()) {
		var ret bool
		return ret
	}
	return *o.Required.Get()
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificateStoresTypesStoreTypeProperty) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Required.Get(), o.Required.IsSet()
}

// HasRequired returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasRequired() bool {
	if o != nil && o.Required.IsSet() {
		return true
	}

	return false
}

// SetRequired gets a reference to the given NullableBool and assigns it to the Required field.
func (o *CertificateStoresTypesStoreTypeProperty) SetRequired(v bool) {
	o.Required.Set(&v)
}

// SetRequiredNil sets the value for Required to be an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) SetRequiredNil() {
	o.Required.Set(nil)
}

// UnsetRequired ensures that no value is present for Required, not even an explicit nil
func (o *CertificateStoresTypesStoreTypeProperty) UnsetRequired() {
	o.Required.Unset()
}

// GetValidationOptions returns the ValidationOptions field value if set, zero value otherwise.
func (o *CertificateStoresTypesStoreTypeProperty) GetValidationOptions() CertificateStoresTypesPropertiesValidationOptions {
	if o == nil || isNil(o.ValidationOptions) {
		var ret CertificateStoresTypesPropertiesValidationOptions
		return ret
	}
	return *o.ValidationOptions
}

// GetValidationOptionsOk returns a tuple with the ValidationOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesStoreTypeProperty) GetValidationOptionsOk() (*CertificateStoresTypesPropertiesValidationOptions, bool) {
	if o == nil || isNil(o.ValidationOptions) {
		return nil, false
	}
	return o.ValidationOptions, true
}

// HasValidationOptions returns a boolean if a field has been set.
func (o *CertificateStoresTypesStoreTypeProperty) HasValidationOptions() bool {
	if o != nil && !isNil(o.ValidationOptions) {
		return true
	}

	return false
}

// SetValidationOptions gets a reference to the given CertificateStoresTypesPropertiesValidationOptions and assigns it to the ValidationOptions field.
func (o *CertificateStoresTypesStoreTypeProperty) SetValidationOptions(v CertificateStoresTypesPropertiesValidationOptions) {
	o.ValidationOptions = &v
}

func (o CertificateStoresTypesStoreTypeProperty) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateStoresTypesStoreTypeProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !isNil(o.StoreTypeId) {
		toSerialize["StoreTypeId"] = o.StoreTypeId
	}
	if o.Name.IsSet() {
		toSerialize["Name"] = o.Name.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["DisplayName"] = o.DisplayName.Get()
	}
	if !isNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if o.DependsOn.IsSet() {
		toSerialize["DependsOn"] = o.DependsOn.Get()
	}
	if o.DefaultValue.IsSet() {
		toSerialize["DefaultValue"] = o.DefaultValue.Get()
	}
	if o.Required.IsSet() {
		toSerialize["Required"] = o.Required.Get()
	}
	if !isNil(o.ValidationOptions) {
		toSerialize["ValidationOptions"] = o.ValidationOptions
	}
	return toSerialize, nil
}

type NullableCertificateStoresTypesStoreTypeProperty struct {
	value *CertificateStoresTypesStoreTypeProperty
	isSet bool
}

func (v NullableCertificateStoresTypesStoreTypeProperty) Get() *CertificateStoresTypesStoreTypeProperty {
	return v.value
}

func (v *NullableCertificateStoresTypesStoreTypeProperty) Set(val *CertificateStoresTypesStoreTypeProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateStoresTypesStoreTypeProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateStoresTypesStoreTypeProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateStoresTypesStoreTypeProperty(val *CertificateStoresTypesStoreTypeProperty) *NullableCertificateStoresTypesStoreTypeProperty {
	return &NullableCertificateStoresTypesStoreTypeProperty{value: val, isSet: true}
}

func (v NullableCertificateStoresTypesStoreTypeProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateStoresTypesStoreTypeProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
