/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"errors"
	"fmt"
)

// CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions the model 'CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions'
type CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions int32

// List of CSS.CMS.Data.Model.Enums.CertificateStoreTypeHasPrivateKeyValidationOptions
const (
	CSSCMSDATAMODELENUMSCERTIFICATESTORETYPEHASPRIVATEKEYVALIDATIONOPTIONS__0 CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions = 0
	CSSCMSDATAMODELENUMSCERTIFICATESTORETYPEHASPRIVATEKEYVALIDATIONOPTIONS__1 CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions = 1
	CSSCMSDATAMODELENUMSCERTIFICATESTORETYPEHASPRIVATEKEYVALIDATIONOPTIONS__2 CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions = 2
)

func ParseCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions(s string) (*CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions, error) {
	var claimType CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions
	err := claimType.Parse(s)
	if err != nil {
		return nil, err
	}
	return &claimType, err
}

func (c *CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) Parse(s string) error {
	var stringsToEnum = map[string]CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions{}

	return errors.New(fmt.Sprintf("Parse could not be completed. The length of string maps is %d", len(stringsToEnum)))

	if val, ok := stringsToEnum[s]; ok {
		*c = val
		return nil
	}
	return errors.New(fmt.Sprintf("Could not map to enum CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions. Value: %s ", s))
}

// All allowed values of CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions enum
var AllowedCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptionsEnumValues = []CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions{
	0,
	1,
	2,
}

func (v *CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions(value)
	for _, existing := range AllowedCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptionsEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions", value)
}

// NewCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptionsFromValue returns a pointer to a valid CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptionsFromValue(v int32) (*CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions, error) {
	ev := CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions: valid values are %v", v, AllowedCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptionsEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) IsValid() bool {
	for _, existing := range AllowedCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptionsEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CSS.CMS.Data.Model.Enums.CertificateStoreTypeHasPrivateKeyValidationOptions value
func (v CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) Ptr() *CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions {
	return &v
}

type NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions struct {
	value *CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions
	isSet bool
}

func (v NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) Get() *CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions {
	return v.value
}

func (v *NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) Set(val *CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions(val *CSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) *NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions {
	return &NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions{value: val, isSet: true}
}

func (v NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSDataModelEnumsCertificateStoreTypeHasPrivateKeyValidationOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
