/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the EventHandlerRegistrationEventHandlerRegistrationCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventHandlerRegistrationEventHandlerRegistrationCreateRequest{}

// EventHandlerRegistrationEventHandlerRegistrationCreateRequest struct for EventHandlerRegistrationEventHandlerRegistrationCreateRequest
type EventHandlerRegistrationEventHandlerRegistrationCreateRequest struct {
	AssemblyName string `json:"AssemblyName"`
}

// NewEventHandlerRegistrationEventHandlerRegistrationCreateRequest instantiates a new EventHandlerRegistrationEventHandlerRegistrationCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventHandlerRegistrationEventHandlerRegistrationCreateRequest(assemblyName string) *EventHandlerRegistrationEventHandlerRegistrationCreateRequest {
	this := EventHandlerRegistrationEventHandlerRegistrationCreateRequest{}
	this.AssemblyName = assemblyName
	return &this
}

// NewEventHandlerRegistrationEventHandlerRegistrationCreateRequestWithDefaults instantiates a new EventHandlerRegistrationEventHandlerRegistrationCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventHandlerRegistrationEventHandlerRegistrationCreateRequestWithDefaults() *EventHandlerRegistrationEventHandlerRegistrationCreateRequest {
	this := EventHandlerRegistrationEventHandlerRegistrationCreateRequest{}
	return &this
}

// GetAssemblyName returns the AssemblyName field value
func (o *EventHandlerRegistrationEventHandlerRegistrationCreateRequest) GetAssemblyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssemblyName
}

// GetAssemblyNameOk returns a tuple with the AssemblyName field value
// and a boolean to check if the value has been set.
func (o *EventHandlerRegistrationEventHandlerRegistrationCreateRequest) GetAssemblyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssemblyName, true
}

// SetAssemblyName sets field value
func (o *EventHandlerRegistrationEventHandlerRegistrationCreateRequest) SetAssemblyName(v string) {
	o.AssemblyName = v
}

func (o EventHandlerRegistrationEventHandlerRegistrationCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventHandlerRegistrationEventHandlerRegistrationCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["AssemblyName"] = o.AssemblyName
	return toSerialize, nil
}

type NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest struct {
	value *EventHandlerRegistrationEventHandlerRegistrationCreateRequest
	isSet bool
}

func (v NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest) Get() *EventHandlerRegistrationEventHandlerRegistrationCreateRequest {
	return v.value
}

func (v *NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest) Set(val *EventHandlerRegistrationEventHandlerRegistrationCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest(val *EventHandlerRegistrationEventHandlerRegistrationCreateRequest) *NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest {
	return &NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest{value: val, isSet: true}
}

func (v NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventHandlerRegistrationEventHandlerRegistrationCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
