/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CSSCMSQueryingCoreComponentsQueryFieldMultiValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CSSCMSQueryingCoreComponentsQueryFieldMultiValue{}

// CSSCMSQueryingCoreComponentsQueryFieldMultiValue struct for CSSCMSQueryingCoreComponentsQueryFieldMultiValue
type CSSCMSQueryingCoreComponentsQueryFieldMultiValue struct {
	FieldDisplayName      NullableString `json:"fieldDisplayName,omitempty"`
	MultiValueDisplayName NullableString `json:"multiValueDisplayName,omitempty"`
	MultiValueName        NullableString `json:"multiValueName,omitempty"`
}

// NewCSSCMSQueryingCoreComponentsQueryFieldMultiValue instantiates a new CSSCMSQueryingCoreComponentsQueryFieldMultiValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSSCMSQueryingCoreComponentsQueryFieldMultiValue() *CSSCMSQueryingCoreComponentsQueryFieldMultiValue {
	this := CSSCMSQueryingCoreComponentsQueryFieldMultiValue{}
	return &this
}

// NewCSSCMSQueryingCoreComponentsQueryFieldMultiValueWithDefaults instantiates a new CSSCMSQueryingCoreComponentsQueryFieldMultiValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSSCMSQueryingCoreComponentsQueryFieldMultiValueWithDefaults() *CSSCMSQueryingCoreComponentsQueryFieldMultiValue {
	this := CSSCMSQueryingCoreComponentsQueryFieldMultiValue{}
	return &this
}

// GetFieldDisplayName returns the FieldDisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) GetFieldDisplayName() string {
	if o == nil || isNil(o.FieldDisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.FieldDisplayName.Get()
}

// GetFieldDisplayNameOk returns a tuple with the FieldDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) GetFieldDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FieldDisplayName.Get(), o.FieldDisplayName.IsSet()
}

// HasFieldDisplayName returns a boolean if a field has been set.
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) HasFieldDisplayName() bool {
	if o != nil && o.FieldDisplayName.IsSet() {
		return true
	}

	return false
}

// SetFieldDisplayName gets a reference to the given NullableString and assigns it to the FieldDisplayName field.
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) SetFieldDisplayName(v string) {
	o.FieldDisplayName.Set(&v)
}

// SetFieldDisplayNameNil sets the value for FieldDisplayName to be an explicit nil
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) SetFieldDisplayNameNil() {
	o.FieldDisplayName.Set(nil)
}

// UnsetFieldDisplayName ensures that no value is present for FieldDisplayName, not even an explicit nil
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) UnsetFieldDisplayName() {
	o.FieldDisplayName.Unset()
}

// GetMultiValueDisplayName returns the MultiValueDisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) GetMultiValueDisplayName() string {
	if o == nil || isNil(o.MultiValueDisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.MultiValueDisplayName.Get()
}

// GetMultiValueDisplayNameOk returns a tuple with the MultiValueDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) GetMultiValueDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MultiValueDisplayName.Get(), o.MultiValueDisplayName.IsSet()
}

// HasMultiValueDisplayName returns a boolean if a field has been set.
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) HasMultiValueDisplayName() bool {
	if o != nil && o.MultiValueDisplayName.IsSet() {
		return true
	}

	return false
}

// SetMultiValueDisplayName gets a reference to the given NullableString and assigns it to the MultiValueDisplayName field.
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) SetMultiValueDisplayName(v string) {
	o.MultiValueDisplayName.Set(&v)
}

// SetMultiValueDisplayNameNil sets the value for MultiValueDisplayName to be an explicit nil
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) SetMultiValueDisplayNameNil() {
	o.MultiValueDisplayName.Set(nil)
}

// UnsetMultiValueDisplayName ensures that no value is present for MultiValueDisplayName, not even an explicit nil
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) UnsetMultiValueDisplayName() {
	o.MultiValueDisplayName.Unset()
}

// GetMultiValueName returns the MultiValueName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) GetMultiValueName() string {
	if o == nil || isNil(o.MultiValueName.Get()) {
		var ret string
		return ret
	}
	return *o.MultiValueName.Get()
}

// GetMultiValueNameOk returns a tuple with the MultiValueName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) GetMultiValueNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MultiValueName.Get(), o.MultiValueName.IsSet()
}

// HasMultiValueName returns a boolean if a field has been set.
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) HasMultiValueName() bool {
	if o != nil && o.MultiValueName.IsSet() {
		return true
	}

	return false
}

// SetMultiValueName gets a reference to the given NullableString and assigns it to the MultiValueName field.
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) SetMultiValueName(v string) {
	o.MultiValueName.Set(&v)
}

// SetMultiValueNameNil sets the value for MultiValueName to be an explicit nil
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) SetMultiValueNameNil() {
	o.MultiValueName.Set(nil)
}

// UnsetMultiValueName ensures that no value is present for MultiValueName, not even an explicit nil
func (o *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) UnsetMultiValueName() {
	o.MultiValueName.Unset()
}

func (o CSSCMSQueryingCoreComponentsQueryFieldMultiValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CSSCMSQueryingCoreComponentsQueryFieldMultiValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FieldDisplayName.IsSet() {
		toSerialize["fieldDisplayName"] = o.FieldDisplayName.Get()
	}
	if o.MultiValueDisplayName.IsSet() {
		toSerialize["multiValueDisplayName"] = o.MultiValueDisplayName.Get()
	}
	if o.MultiValueName.IsSet() {
		toSerialize["multiValueName"] = o.MultiValueName.Get()
	}
	return toSerialize, nil
}

type NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue struct {
	value *CSSCMSQueryingCoreComponentsQueryFieldMultiValue
	isSet bool
}

func (v NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue) Get() *CSSCMSQueryingCoreComponentsQueryFieldMultiValue {
	return v.value
}

func (v *NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue) Set(val *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue(val *CSSCMSQueryingCoreComponentsQueryFieldMultiValue) *NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue {
	return &NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue{value: val, isSet: true}
}

func (v NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSQueryingCoreComponentsQueryFieldMultiValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
