/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the EnrollmentPatternsAlgorithmsKeyInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrollmentPatternsAlgorithmsKeyInfoRequest{}

// EnrollmentPatternsAlgorithmsKeyInfoRequest struct for EnrollmentPatternsAlgorithmsKeyInfoRequest
type EnrollmentPatternsAlgorithmsKeyInfoRequest struct {
	ECDSA   *EnrollmentPatternsAlgorithmsAlgorithmDataRequest `json:"ECDSA,omitempty"`
	RSA     *EnrollmentPatternsAlgorithmsAlgorithmDataRequest `json:"RSA,omitempty"`
	Ed448   *EnrollmentPatternsAlgorithmsAlgorithmDataRequest `json:"Ed448,omitempty"`
	Ed25519 *EnrollmentPatternsAlgorithmsAlgorithmDataRequest `json:"Ed25519,omitempty"`
}

// NewEnrollmentPatternsAlgorithmsKeyInfoRequest instantiates a new EnrollmentPatternsAlgorithmsKeyInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrollmentPatternsAlgorithmsKeyInfoRequest() *EnrollmentPatternsAlgorithmsKeyInfoRequest {
	this := EnrollmentPatternsAlgorithmsKeyInfoRequest{}
	return &this
}

// NewEnrollmentPatternsAlgorithmsKeyInfoRequestWithDefaults instantiates a new EnrollmentPatternsAlgorithmsKeyInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrollmentPatternsAlgorithmsKeyInfoRequestWithDefaults() *EnrollmentPatternsAlgorithmsKeyInfoRequest {
	this := EnrollmentPatternsAlgorithmsKeyInfoRequest{}
	return &this
}

// GetECDSA returns the ECDSA field value if set, zero value otherwise.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetECDSA() EnrollmentPatternsAlgorithmsAlgorithmDataRequest {
	if o == nil || isNil(o.ECDSA) {
		var ret EnrollmentPatternsAlgorithmsAlgorithmDataRequest
		return ret
	}
	return *o.ECDSA
}

// GetECDSAOk returns a tuple with the ECDSA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetECDSAOk() (*EnrollmentPatternsAlgorithmsAlgorithmDataRequest, bool) {
	if o == nil || isNil(o.ECDSA) {
		return nil, false
	}
	return o.ECDSA, true
}

// HasECDSA returns a boolean if a field has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) HasECDSA() bool {
	if o != nil && !isNil(o.ECDSA) {
		return true
	}

	return false
}

// SetECDSA gets a reference to the given EnrollmentPatternsAlgorithmsAlgorithmDataRequest and assigns it to the ECDSA field.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) SetECDSA(v EnrollmentPatternsAlgorithmsAlgorithmDataRequest) {
	o.ECDSA = &v
}

// GetRSA returns the RSA field value if set, zero value otherwise.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetRSA() EnrollmentPatternsAlgorithmsAlgorithmDataRequest {
	if o == nil || isNil(o.RSA) {
		var ret EnrollmentPatternsAlgorithmsAlgorithmDataRequest
		return ret
	}
	return *o.RSA
}

// GetRSAOk returns a tuple with the RSA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetRSAOk() (*EnrollmentPatternsAlgorithmsAlgorithmDataRequest, bool) {
	if o == nil || isNil(o.RSA) {
		return nil, false
	}
	return o.RSA, true
}

// HasRSA returns a boolean if a field has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) HasRSA() bool {
	if o != nil && !isNil(o.RSA) {
		return true
	}

	return false
}

// SetRSA gets a reference to the given EnrollmentPatternsAlgorithmsAlgorithmDataRequest and assigns it to the RSA field.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) SetRSA(v EnrollmentPatternsAlgorithmsAlgorithmDataRequest) {
	o.RSA = &v
}

// GetEd448 returns the Ed448 field value if set, zero value otherwise.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetEd448() EnrollmentPatternsAlgorithmsAlgorithmDataRequest {
	if o == nil || isNil(o.Ed448) {
		var ret EnrollmentPatternsAlgorithmsAlgorithmDataRequest
		return ret
	}
	return *o.Ed448
}

// GetEd448Ok returns a tuple with the Ed448 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetEd448Ok() (*EnrollmentPatternsAlgorithmsAlgorithmDataRequest, bool) {
	if o == nil || isNil(o.Ed448) {
		return nil, false
	}
	return o.Ed448, true
}

// HasEd448 returns a boolean if a field has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) HasEd448() bool {
	if o != nil && !isNil(o.Ed448) {
		return true
	}

	return false
}

// SetEd448 gets a reference to the given EnrollmentPatternsAlgorithmsAlgorithmDataRequest and assigns it to the Ed448 field.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) SetEd448(v EnrollmentPatternsAlgorithmsAlgorithmDataRequest) {
	o.Ed448 = &v
}

// GetEd25519 returns the Ed25519 field value if set, zero value otherwise.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetEd25519() EnrollmentPatternsAlgorithmsAlgorithmDataRequest {
	if o == nil || isNil(o.Ed25519) {
		var ret EnrollmentPatternsAlgorithmsAlgorithmDataRequest
		return ret
	}
	return *o.Ed25519
}

// GetEd25519Ok returns a tuple with the Ed25519 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) GetEd25519Ok() (*EnrollmentPatternsAlgorithmsAlgorithmDataRequest, bool) {
	if o == nil || isNil(o.Ed25519) {
		return nil, false
	}
	return o.Ed25519, true
}

// HasEd25519 returns a boolean if a field has been set.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) HasEd25519() bool {
	if o != nil && !isNil(o.Ed25519) {
		return true
	}

	return false
}

// SetEd25519 gets a reference to the given EnrollmentPatternsAlgorithmsAlgorithmDataRequest and assigns it to the Ed25519 field.
func (o *EnrollmentPatternsAlgorithmsKeyInfoRequest) SetEd25519(v EnrollmentPatternsAlgorithmsAlgorithmDataRequest) {
	o.Ed25519 = &v
}

func (o EnrollmentPatternsAlgorithmsKeyInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrollmentPatternsAlgorithmsKeyInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ECDSA) {
		toSerialize["ECDSA"] = o.ECDSA
	}
	if !isNil(o.RSA) {
		toSerialize["RSA"] = o.RSA
	}
	if !isNil(o.Ed448) {
		toSerialize["Ed448"] = o.Ed448
	}
	if !isNil(o.Ed25519) {
		toSerialize["Ed25519"] = o.Ed25519
	}
	return toSerialize, nil
}

type NullableEnrollmentPatternsAlgorithmsKeyInfoRequest struct {
	value *EnrollmentPatternsAlgorithmsKeyInfoRequest
	isSet bool
}

func (v NullableEnrollmentPatternsAlgorithmsKeyInfoRequest) Get() *EnrollmentPatternsAlgorithmsKeyInfoRequest {
	return v.value
}

func (v *NullableEnrollmentPatternsAlgorithmsKeyInfoRequest) Set(val *EnrollmentPatternsAlgorithmsKeyInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrollmentPatternsAlgorithmsKeyInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrollmentPatternsAlgorithmsKeyInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrollmentPatternsAlgorithmsKeyInfoRequest(val *EnrollmentPatternsAlgorithmsKeyInfoRequest) *NullableEnrollmentPatternsAlgorithmsKeyInfoRequest {
	return &NullableEnrollmentPatternsAlgorithmsKeyInfoRequest{value: val, isSet: true}
}

func (v NullableEnrollmentPatternsAlgorithmsKeyInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrollmentPatternsAlgorithmsKeyInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
