/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CSSCMSDataModelModelsPkcs12CertificateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CSSCMSDataModelModelsPkcs12CertificateResponse{}

// CSSCMSDataModelModelsPkcs12CertificateResponse struct for CSSCMSDataModelModelsPkcs12CertificateResponse
type CSSCMSDataModelModelsPkcs12CertificateResponse struct {
	SerialNumber              NullableString    `json:"SerialNumber,omitempty"`
	IssuerDN                  NullableString    `json:"IssuerDN,omitempty"`
	Thumbprint                NullableString    `json:"Thumbprint,omitempty"`
	KeyfactorId               *int32            `json:"KeyfactorId,omitempty"`
	Pkcs12Blob                NullableString    `json:"Pkcs12Blob,omitempty"`
	Password                  NullableString    `json:"Password,omitempty"`
	WorkflowInstanceId        *string           `json:"WorkflowInstanceId,omitempty"`
	WorkflowReferenceId       *int64            `json:"WorkflowReferenceId,omitempty"`
	StoreIdsInvalidForRenewal []string          `json:"StoreIdsInvalidForRenewal,omitempty"`
	ChainFailedToBuild        *bool             `json:"ChainFailedToBuild,omitempty"`
	KeyfactorRequestId        *int32            `json:"KeyfactorRequestId,omitempty"`
	RequestDisposition        NullableString    `json:"RequestDisposition,omitempty"`
	DispositionMessage        NullableString    `json:"DispositionMessage,omitempty"`
	EnrollmentContext         map[string]string `json:"EnrollmentContext,omitempty"`
}

// NewCSSCMSDataModelModelsPkcs12CertificateResponse instantiates a new CSSCMSDataModelModelsPkcs12CertificateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSSCMSDataModelModelsPkcs12CertificateResponse() *CSSCMSDataModelModelsPkcs12CertificateResponse {
	this := CSSCMSDataModelModelsPkcs12CertificateResponse{}
	return &this
}

// NewCSSCMSDataModelModelsPkcs12CertificateResponseWithDefaults instantiates a new CSSCMSDataModelModelsPkcs12CertificateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSSCMSDataModelModelsPkcs12CertificateResponseWithDefaults() *CSSCMSDataModelModelsPkcs12CertificateResponse {
	this := CSSCMSDataModelModelsPkcs12CertificateResponse{}
	return &this
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetSerialNumber() string {
	if o == nil || isNil(o.SerialNumber.Get()) {
		var ret string
		return ret
	}
	return *o.SerialNumber.Get()
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SerialNumber.Get(), o.SerialNumber.IsSet()
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasSerialNumber() bool {
	if o != nil && o.SerialNumber.IsSet() {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given NullableString and assigns it to the SerialNumber field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetSerialNumber(v string) {
	o.SerialNumber.Set(&v)
}

// SetSerialNumberNil sets the value for SerialNumber to be an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetSerialNumberNil() {
	o.SerialNumber.Set(nil)
}

// UnsetSerialNumber ensures that no value is present for SerialNumber, not even an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) UnsetSerialNumber() {
	o.SerialNumber.Unset()
}

// GetIssuerDN returns the IssuerDN field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetIssuerDN() string {
	if o == nil || isNil(o.IssuerDN.Get()) {
		var ret string
		return ret
	}
	return *o.IssuerDN.Get()
}

// GetIssuerDNOk returns a tuple with the IssuerDN field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetIssuerDNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IssuerDN.Get(), o.IssuerDN.IsSet()
}

// HasIssuerDN returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasIssuerDN() bool {
	if o != nil && o.IssuerDN.IsSet() {
		return true
	}

	return false
}

// SetIssuerDN gets a reference to the given NullableString and assigns it to the IssuerDN field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetIssuerDN(v string) {
	o.IssuerDN.Set(&v)
}

// SetIssuerDNNil sets the value for IssuerDN to be an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetIssuerDNNil() {
	o.IssuerDN.Set(nil)
}

// UnsetIssuerDN ensures that no value is present for IssuerDN, not even an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) UnsetIssuerDN() {
	o.IssuerDN.Unset()
}

// GetThumbprint returns the Thumbprint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetThumbprint() string {
	if o == nil || isNil(o.Thumbprint.Get()) {
		var ret string
		return ret
	}
	return *o.Thumbprint.Get()
}

// GetThumbprintOk returns a tuple with the Thumbprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetThumbprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Thumbprint.Get(), o.Thumbprint.IsSet()
}

// HasThumbprint returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasThumbprint() bool {
	if o != nil && o.Thumbprint.IsSet() {
		return true
	}

	return false
}

// SetThumbprint gets a reference to the given NullableString and assigns it to the Thumbprint field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetThumbprint(v string) {
	o.Thumbprint.Set(&v)
}

// SetThumbprintNil sets the value for Thumbprint to be an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetThumbprintNil() {
	o.Thumbprint.Set(nil)
}

// UnsetThumbprint ensures that no value is present for Thumbprint, not even an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) UnsetThumbprint() {
	o.Thumbprint.Unset()
}

// GetKeyfactorId returns the KeyfactorId field value if set, zero value otherwise.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetKeyfactorId() int32 {
	if o == nil || isNil(o.KeyfactorId) {
		var ret int32
		return ret
	}
	return *o.KeyfactorId
}

// GetKeyfactorIdOk returns a tuple with the KeyfactorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetKeyfactorIdOk() (*int32, bool) {
	if o == nil || isNil(o.KeyfactorId) {
		return nil, false
	}
	return o.KeyfactorId, true
}

// HasKeyfactorId returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasKeyfactorId() bool {
	if o != nil && !isNil(o.KeyfactorId) {
		return true
	}

	return false
}

// SetKeyfactorId gets a reference to the given int32 and assigns it to the KeyfactorId field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetKeyfactorId(v int32) {
	o.KeyfactorId = &v
}

// GetPkcs12Blob returns the Pkcs12Blob field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetPkcs12Blob() string {
	if o == nil || isNil(o.Pkcs12Blob.Get()) {
		var ret string
		return ret
	}
	return *o.Pkcs12Blob.Get()
}

// GetPkcs12BlobOk returns a tuple with the Pkcs12Blob field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetPkcs12BlobOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pkcs12Blob.Get(), o.Pkcs12Blob.IsSet()
}

// HasPkcs12Blob returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasPkcs12Blob() bool {
	if o != nil && o.Pkcs12Blob.IsSet() {
		return true
	}

	return false
}

// SetPkcs12Blob gets a reference to the given NullableString and assigns it to the Pkcs12Blob field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetPkcs12Blob(v string) {
	o.Pkcs12Blob.Set(&v)
}

// SetPkcs12BlobNil sets the value for Pkcs12Blob to be an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetPkcs12BlobNil() {
	o.Pkcs12Blob.Set(nil)
}

// UnsetPkcs12Blob ensures that no value is present for Pkcs12Blob, not even an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) UnsetPkcs12Blob() {
	o.Pkcs12Blob.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetPassword() string {
	if o == nil || isNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetPassword(v string) {
	o.Password.Set(&v)
}

// SetPasswordNil sets the value for Password to be an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) UnsetPassword() {
	o.Password.Unset()
}

// GetWorkflowInstanceId returns the WorkflowInstanceId field value if set, zero value otherwise.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetWorkflowInstanceId() string {
	if o == nil || isNil(o.WorkflowInstanceId) {
		var ret string
		return ret
	}
	return *o.WorkflowInstanceId
}

// GetWorkflowInstanceIdOk returns a tuple with the WorkflowInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetWorkflowInstanceIdOk() (*string, bool) {
	if o == nil || isNil(o.WorkflowInstanceId) {
		return nil, false
	}
	return o.WorkflowInstanceId, true
}

// HasWorkflowInstanceId returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasWorkflowInstanceId() bool {
	if o != nil && !isNil(o.WorkflowInstanceId) {
		return true
	}

	return false
}

// SetWorkflowInstanceId gets a reference to the given string and assigns it to the WorkflowInstanceId field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetWorkflowInstanceId(v string) {
	o.WorkflowInstanceId = &v
}

// GetWorkflowReferenceId returns the WorkflowReferenceId field value if set, zero value otherwise.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetWorkflowReferenceId() int64 {
	if o == nil || isNil(o.WorkflowReferenceId) {
		var ret int64
		return ret
	}
	return *o.WorkflowReferenceId
}

// GetWorkflowReferenceIdOk returns a tuple with the WorkflowReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetWorkflowReferenceIdOk() (*int64, bool) {
	if o == nil || isNil(o.WorkflowReferenceId) {
		return nil, false
	}
	return o.WorkflowReferenceId, true
}

// HasWorkflowReferenceId returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasWorkflowReferenceId() bool {
	if o != nil && !isNil(o.WorkflowReferenceId) {
		return true
	}

	return false
}

// SetWorkflowReferenceId gets a reference to the given int64 and assigns it to the WorkflowReferenceId field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetWorkflowReferenceId(v int64) {
	o.WorkflowReferenceId = &v
}

// GetStoreIdsInvalidForRenewal returns the StoreIdsInvalidForRenewal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetStoreIdsInvalidForRenewal() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.StoreIdsInvalidForRenewal
}

// GetStoreIdsInvalidForRenewalOk returns a tuple with the StoreIdsInvalidForRenewal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetStoreIdsInvalidForRenewalOk() ([]string, bool) {
	if o == nil || isNil(o.StoreIdsInvalidForRenewal) {
		return nil, false
	}
	return o.StoreIdsInvalidForRenewal, true
}

// HasStoreIdsInvalidForRenewal returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasStoreIdsInvalidForRenewal() bool {
	if o != nil && isNil(o.StoreIdsInvalidForRenewal) {
		return true
	}

	return false
}

// SetStoreIdsInvalidForRenewal gets a reference to the given []string and assigns it to the StoreIdsInvalidForRenewal field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetStoreIdsInvalidForRenewal(v []string) {
	o.StoreIdsInvalidForRenewal = v
}

// GetChainFailedToBuild returns the ChainFailedToBuild field value if set, zero value otherwise.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetChainFailedToBuild() bool {
	if o == nil || isNil(o.ChainFailedToBuild) {
		var ret bool
		return ret
	}
	return *o.ChainFailedToBuild
}

// GetChainFailedToBuildOk returns a tuple with the ChainFailedToBuild field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetChainFailedToBuildOk() (*bool, bool) {
	if o == nil || isNil(o.ChainFailedToBuild) {
		return nil, false
	}
	return o.ChainFailedToBuild, true
}

// HasChainFailedToBuild returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasChainFailedToBuild() bool {
	if o != nil && !isNil(o.ChainFailedToBuild) {
		return true
	}

	return false
}

// SetChainFailedToBuild gets a reference to the given bool and assigns it to the ChainFailedToBuild field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetChainFailedToBuild(v bool) {
	o.ChainFailedToBuild = &v
}

// GetKeyfactorRequestId returns the KeyfactorRequestId field value if set, zero value otherwise.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetKeyfactorRequestId() int32 {
	if o == nil || isNil(o.KeyfactorRequestId) {
		var ret int32
		return ret
	}
	return *o.KeyfactorRequestId
}

// GetKeyfactorRequestIdOk returns a tuple with the KeyfactorRequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetKeyfactorRequestIdOk() (*int32, bool) {
	if o == nil || isNil(o.KeyfactorRequestId) {
		return nil, false
	}
	return o.KeyfactorRequestId, true
}

// HasKeyfactorRequestId returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasKeyfactorRequestId() bool {
	if o != nil && !isNil(o.KeyfactorRequestId) {
		return true
	}

	return false
}

// SetKeyfactorRequestId gets a reference to the given int32 and assigns it to the KeyfactorRequestId field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetKeyfactorRequestId(v int32) {
	o.KeyfactorRequestId = &v
}

// GetRequestDisposition returns the RequestDisposition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetRequestDisposition() string {
	if o == nil || isNil(o.RequestDisposition.Get()) {
		var ret string
		return ret
	}
	return *o.RequestDisposition.Get()
}

// GetRequestDispositionOk returns a tuple with the RequestDisposition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetRequestDispositionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestDisposition.Get(), o.RequestDisposition.IsSet()
}

// HasRequestDisposition returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasRequestDisposition() bool {
	if o != nil && o.RequestDisposition.IsSet() {
		return true
	}

	return false
}

// SetRequestDisposition gets a reference to the given NullableString and assigns it to the RequestDisposition field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetRequestDisposition(v string) {
	o.RequestDisposition.Set(&v)
}

// SetRequestDispositionNil sets the value for RequestDisposition to be an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetRequestDispositionNil() {
	o.RequestDisposition.Set(nil)
}

// UnsetRequestDisposition ensures that no value is present for RequestDisposition, not even an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) UnsetRequestDisposition() {
	o.RequestDisposition.Unset()
}

// GetDispositionMessage returns the DispositionMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetDispositionMessage() string {
	if o == nil || isNil(o.DispositionMessage.Get()) {
		var ret string
		return ret
	}
	return *o.DispositionMessage.Get()
}

// GetDispositionMessageOk returns a tuple with the DispositionMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetDispositionMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DispositionMessage.Get(), o.DispositionMessage.IsSet()
}

// HasDispositionMessage returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasDispositionMessage() bool {
	if o != nil && o.DispositionMessage.IsSet() {
		return true
	}

	return false
}

// SetDispositionMessage gets a reference to the given NullableString and assigns it to the DispositionMessage field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetDispositionMessage(v string) {
	o.DispositionMessage.Set(&v)
}

// SetDispositionMessageNil sets the value for DispositionMessage to be an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetDispositionMessageNil() {
	o.DispositionMessage.Set(nil)
}

// UnsetDispositionMessage ensures that no value is present for DispositionMessage, not even an explicit nil
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) UnsetDispositionMessage() {
	o.DispositionMessage.Unset()
}

// GetEnrollmentContext returns the EnrollmentContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetEnrollmentContext() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.EnrollmentContext
}

// GetEnrollmentContextOk returns a tuple with the EnrollmentContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) GetEnrollmentContextOk() (*map[string]string, bool) {
	if o == nil || isNil(o.EnrollmentContext) {
		return nil, false
	}
	return &o.EnrollmentContext, true
}

// HasEnrollmentContext returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) HasEnrollmentContext() bool {
	if o != nil && isNil(o.EnrollmentContext) {
		return true
	}

	return false
}

// SetEnrollmentContext gets a reference to the given map[string]string and assigns it to the EnrollmentContext field.
func (o *CSSCMSDataModelModelsPkcs12CertificateResponse) SetEnrollmentContext(v map[string]string) {
	o.EnrollmentContext = v
}

func (o CSSCMSDataModelModelsPkcs12CertificateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CSSCMSDataModelModelsPkcs12CertificateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SerialNumber.IsSet() {
		toSerialize["SerialNumber"] = o.SerialNumber.Get()
	}
	if o.IssuerDN.IsSet() {
		toSerialize["IssuerDN"] = o.IssuerDN.Get()
	}
	if o.Thumbprint.IsSet() {
		toSerialize["Thumbprint"] = o.Thumbprint.Get()
	}
	if !isNil(o.KeyfactorId) {
		toSerialize["KeyfactorId"] = o.KeyfactorId
	}
	if o.Pkcs12Blob.IsSet() {
		toSerialize["Pkcs12Blob"] = o.Pkcs12Blob.Get()
	}
	if o.Password.IsSet() {
		toSerialize["Password"] = o.Password.Get()
	}
	if !isNil(o.WorkflowInstanceId) {
		toSerialize["WorkflowInstanceId"] = o.WorkflowInstanceId
	}
	if !isNil(o.WorkflowReferenceId) {
		toSerialize["WorkflowReferenceId"] = o.WorkflowReferenceId
	}
	if o.StoreIdsInvalidForRenewal != nil {
		toSerialize["StoreIdsInvalidForRenewal"] = o.StoreIdsInvalidForRenewal
	}
	if !isNil(o.ChainFailedToBuild) {
		toSerialize["ChainFailedToBuild"] = o.ChainFailedToBuild
	}
	if !isNil(o.KeyfactorRequestId) {
		toSerialize["KeyfactorRequestId"] = o.KeyfactorRequestId
	}
	if o.RequestDisposition.IsSet() {
		toSerialize["RequestDisposition"] = o.RequestDisposition.Get()
	}
	if o.DispositionMessage.IsSet() {
		toSerialize["DispositionMessage"] = o.DispositionMessage.Get()
	}
	if o.EnrollmentContext != nil {
		toSerialize["EnrollmentContext"] = o.EnrollmentContext
	}
	return toSerialize, nil
}

type NullableCSSCMSDataModelModelsPkcs12CertificateResponse struct {
	value *CSSCMSDataModelModelsPkcs12CertificateResponse
	isSet bool
}

func (v NullableCSSCMSDataModelModelsPkcs12CertificateResponse) Get() *CSSCMSDataModelModelsPkcs12CertificateResponse {
	return v.value
}

func (v *NullableCSSCMSDataModelModelsPkcs12CertificateResponse) Set(val *CSSCMSDataModelModelsPkcs12CertificateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSDataModelModelsPkcs12CertificateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSDataModelModelsPkcs12CertificateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSDataModelModelsPkcs12CertificateResponse(val *CSSCMSDataModelModelsPkcs12CertificateResponse) *NullableCSSCMSDataModelModelsPkcs12CertificateResponse {
	return &NullableCSSCMSDataModelModelsPkcs12CertificateResponse{value: val, isSet: true}
}

func (v NullableCSSCMSDataModelModelsPkcs12CertificateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSDataModelModelsPkcs12CertificateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
