/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CertificateStoresTypesSupportedOperations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateStoresTypesSupportedOperations{}

// CertificateStoresTypesSupportedOperations struct for CertificateStoresTypesSupportedOperations
type CertificateStoresTypesSupportedOperations struct {
	Add        *bool `json:"Add,omitempty"`
	Create     *bool `json:"Create,omitempty"`
	Discovery  *bool `json:"Discovery,omitempty"`
	Enrollment *bool `json:"Enrollment,omitempty"`
	Remove     *bool `json:"Remove,omitempty"`
}

// NewCertificateStoresTypesSupportedOperations instantiates a new CertificateStoresTypesSupportedOperations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateStoresTypesSupportedOperations() *CertificateStoresTypesSupportedOperations {
	this := CertificateStoresTypesSupportedOperations{}
	return &this
}

// NewCertificateStoresTypesSupportedOperationsWithDefaults instantiates a new CertificateStoresTypesSupportedOperations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateStoresTypesSupportedOperationsWithDefaults() *CertificateStoresTypesSupportedOperations {
	this := CertificateStoresTypesSupportedOperations{}
	return &this
}

// GetAdd returns the Add field value if set, zero value otherwise.
func (o *CertificateStoresTypesSupportedOperations) GetAdd() bool {
	if o == nil || isNil(o.Add) {
		var ret bool
		return ret
	}
	return *o.Add
}

// GetAddOk returns a tuple with the Add field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesSupportedOperations) GetAddOk() (*bool, bool) {
	if o == nil || isNil(o.Add) {
		return nil, false
	}
	return o.Add, true
}

// HasAdd returns a boolean if a field has been set.
func (o *CertificateStoresTypesSupportedOperations) HasAdd() bool {
	if o != nil && !isNil(o.Add) {
		return true
	}

	return false
}

// SetAdd gets a reference to the given bool and assigns it to the Add field.
func (o *CertificateStoresTypesSupportedOperations) SetAdd(v bool) {
	o.Add = &v
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *CertificateStoresTypesSupportedOperations) GetCreate() bool {
	if o == nil || isNil(o.Create) {
		var ret bool
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesSupportedOperations) GetCreateOk() (*bool, bool) {
	if o == nil || isNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *CertificateStoresTypesSupportedOperations) HasCreate() bool {
	if o != nil && !isNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given bool and assigns it to the Create field.
func (o *CertificateStoresTypesSupportedOperations) SetCreate(v bool) {
	o.Create = &v
}

// GetDiscovery returns the Discovery field value if set, zero value otherwise.
func (o *CertificateStoresTypesSupportedOperations) GetDiscovery() bool {
	if o == nil || isNil(o.Discovery) {
		var ret bool
		return ret
	}
	return *o.Discovery
}

// GetDiscoveryOk returns a tuple with the Discovery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesSupportedOperations) GetDiscoveryOk() (*bool, bool) {
	if o == nil || isNil(o.Discovery) {
		return nil, false
	}
	return o.Discovery, true
}

// HasDiscovery returns a boolean if a field has been set.
func (o *CertificateStoresTypesSupportedOperations) HasDiscovery() bool {
	if o != nil && !isNil(o.Discovery) {
		return true
	}

	return false
}

// SetDiscovery gets a reference to the given bool and assigns it to the Discovery field.
func (o *CertificateStoresTypesSupportedOperations) SetDiscovery(v bool) {
	o.Discovery = &v
}

// GetEnrollment returns the Enrollment field value if set, zero value otherwise.
func (o *CertificateStoresTypesSupportedOperations) GetEnrollment() bool {
	if o == nil || isNil(o.Enrollment) {
		var ret bool
		return ret
	}
	return *o.Enrollment
}

// GetEnrollmentOk returns a tuple with the Enrollment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesSupportedOperations) GetEnrollmentOk() (*bool, bool) {
	if o == nil || isNil(o.Enrollment) {
		return nil, false
	}
	return o.Enrollment, true
}

// HasEnrollment returns a boolean if a field has been set.
func (o *CertificateStoresTypesSupportedOperations) HasEnrollment() bool {
	if o != nil && !isNil(o.Enrollment) {
		return true
	}

	return false
}

// SetEnrollment gets a reference to the given bool and assigns it to the Enrollment field.
func (o *CertificateStoresTypesSupportedOperations) SetEnrollment(v bool) {
	o.Enrollment = &v
}

// GetRemove returns the Remove field value if set, zero value otherwise.
func (o *CertificateStoresTypesSupportedOperations) GetRemove() bool {
	if o == nil || isNil(o.Remove) {
		var ret bool
		return ret
	}
	return *o.Remove
}

// GetRemoveOk returns a tuple with the Remove field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesSupportedOperations) GetRemoveOk() (*bool, bool) {
	if o == nil || isNil(o.Remove) {
		return nil, false
	}
	return o.Remove, true
}

// HasRemove returns a boolean if a field has been set.
func (o *CertificateStoresTypesSupportedOperations) HasRemove() bool {
	if o != nil && !isNil(o.Remove) {
		return true
	}

	return false
}

// SetRemove gets a reference to the given bool and assigns it to the Remove field.
func (o *CertificateStoresTypesSupportedOperations) SetRemove(v bool) {
	o.Remove = &v
}

func (o CertificateStoresTypesSupportedOperations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateStoresTypesSupportedOperations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Add) {
		toSerialize["Add"] = o.Add
	}
	if !isNil(o.Create) {
		toSerialize["Create"] = o.Create
	}
	if !isNil(o.Discovery) {
		toSerialize["Discovery"] = o.Discovery
	}
	if !isNil(o.Enrollment) {
		toSerialize["Enrollment"] = o.Enrollment
	}
	if !isNil(o.Remove) {
		toSerialize["Remove"] = o.Remove
	}
	return toSerialize, nil
}

type NullableCertificateStoresTypesSupportedOperations struct {
	value *CertificateStoresTypesSupportedOperations
	isSet bool
}

func (v NullableCertificateStoresTypesSupportedOperations) Get() *CertificateStoresTypesSupportedOperations {
	return v.value
}

func (v *NullableCertificateStoresTypesSupportedOperations) Set(val *CertificateStoresTypesSupportedOperations) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateStoresTypesSupportedOperations) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateStoresTypesSupportedOperations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateStoresTypesSupportedOperations(val *CertificateStoresTypesSupportedOperations) *NullableCertificateStoresTypesSupportedOperations {
	return &NullableCertificateStoresTypesSupportedOperations{value: val, isSet: true}
}

func (v NullableCertificateStoresTypesSupportedOperations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateStoresTypesSupportedOperations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
