/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the AppSettingsAppSettingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppSettingsAppSettingResponse{}

// AppSettingsAppSettingResponse struct for AppSettingsAppSettingResponse
type AppSettingsAppSettingResponse struct {
	Id          *int32         `json:"Id,omitempty"`
	DisplayName NullableString `json:"DisplayName,omitempty"`
	ShortName   NullableString `json:"ShortName,omitempty"`
	Description NullableString `json:"Description,omitempty"`
	Value       NullableString `json:"Value,omitempty"`
	ValueType   NullableString `json:"ValueType,omitempty"`
}

// NewAppSettingsAppSettingResponse instantiates a new AppSettingsAppSettingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppSettingsAppSettingResponse() *AppSettingsAppSettingResponse {
	this := AppSettingsAppSettingResponse{}
	return &this
}

// NewAppSettingsAppSettingResponseWithDefaults instantiates a new AppSettingsAppSettingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppSettingsAppSettingResponseWithDefaults() *AppSettingsAppSettingResponse {
	this := AppSettingsAppSettingResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AppSettingsAppSettingResponse) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppSettingsAppSettingResponse) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AppSettingsAppSettingResponse) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *AppSettingsAppSettingResponse) SetId(v int32) {
	o.Id = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppSettingsAppSettingResponse) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppSettingsAppSettingResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *AppSettingsAppSettingResponse) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *AppSettingsAppSettingResponse) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *AppSettingsAppSettingResponse) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *AppSettingsAppSettingResponse) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetShortName returns the ShortName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppSettingsAppSettingResponse) GetShortName() string {
	if o == nil || isNil(o.ShortName.Get()) {
		var ret string
		return ret
	}
	return *o.ShortName.Get()
}

// GetShortNameOk returns a tuple with the ShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppSettingsAppSettingResponse) GetShortNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShortName.Get(), o.ShortName.IsSet()
}

// HasShortName returns a boolean if a field has been set.
func (o *AppSettingsAppSettingResponse) HasShortName() bool {
	if o != nil && o.ShortName.IsSet() {
		return true
	}

	return false
}

// SetShortName gets a reference to the given NullableString and assigns it to the ShortName field.
func (o *AppSettingsAppSettingResponse) SetShortName(v string) {
	o.ShortName.Set(&v)
}

// SetShortNameNil sets the value for ShortName to be an explicit nil
func (o *AppSettingsAppSettingResponse) SetShortNameNil() {
	o.ShortName.Set(nil)
}

// UnsetShortName ensures that no value is present for ShortName, not even an explicit nil
func (o *AppSettingsAppSettingResponse) UnsetShortName() {
	o.ShortName.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppSettingsAppSettingResponse) GetDescription() string {
	if o == nil || isNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppSettingsAppSettingResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *AppSettingsAppSettingResponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *AppSettingsAppSettingResponse) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *AppSettingsAppSettingResponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *AppSettingsAppSettingResponse) UnsetDescription() {
	o.Description.Unset()
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppSettingsAppSettingResponse) GetValue() string {
	if o == nil || isNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppSettingsAppSettingResponse) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *AppSettingsAppSettingResponse) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *AppSettingsAppSettingResponse) SetValue(v string) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *AppSettingsAppSettingResponse) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *AppSettingsAppSettingResponse) UnsetValue() {
	o.Value.Unset()
}

// GetValueType returns the ValueType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppSettingsAppSettingResponse) GetValueType() string {
	if o == nil || isNil(o.ValueType.Get()) {
		var ret string
		return ret
	}
	return *o.ValueType.Get()
}

// GetValueTypeOk returns a tuple with the ValueType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppSettingsAppSettingResponse) GetValueTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValueType.Get(), o.ValueType.IsSet()
}

// HasValueType returns a boolean if a field has been set.
func (o *AppSettingsAppSettingResponse) HasValueType() bool {
	if o != nil && o.ValueType.IsSet() {
		return true
	}

	return false
}

// SetValueType gets a reference to the given NullableString and assigns it to the ValueType field.
func (o *AppSettingsAppSettingResponse) SetValueType(v string) {
	o.ValueType.Set(&v)
}

// SetValueTypeNil sets the value for ValueType to be an explicit nil
func (o *AppSettingsAppSettingResponse) SetValueTypeNil() {
	o.ValueType.Set(nil)
}

// UnsetValueType ensures that no value is present for ValueType, not even an explicit nil
func (o *AppSettingsAppSettingResponse) UnsetValueType() {
	o.ValueType.Unset()
}

func (o AppSettingsAppSettingResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppSettingsAppSettingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if o.DisplayName.IsSet() {
		toSerialize["DisplayName"] = o.DisplayName.Get()
	}
	if o.ShortName.IsSet() {
		toSerialize["ShortName"] = o.ShortName.Get()
	}
	if o.Description.IsSet() {
		toSerialize["Description"] = o.Description.Get()
	}
	if o.Value.IsSet() {
		toSerialize["Value"] = o.Value.Get()
	}
	if o.ValueType.IsSet() {
		toSerialize["ValueType"] = o.ValueType.Get()
	}
	return toSerialize, nil
}

type NullableAppSettingsAppSettingResponse struct {
	value *AppSettingsAppSettingResponse
	isSet bool
}

func (v NullableAppSettingsAppSettingResponse) Get() *AppSettingsAppSettingResponse {
	return v.value
}

func (v *NullableAppSettingsAppSettingResponse) Set(val *AppSettingsAppSettingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppSettingsAppSettingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppSettingsAppSettingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppSettingsAppSettingResponse(val *AppSettingsAppSettingResponse) *NullableAppSettingsAppSettingResponse {
	return &NullableAppSettingsAppSettingResponse{value: val, isSet: true}
}

func (v NullableAppSettingsAppSettingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppSettingsAppSettingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
