/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// checks if the CertificatesExcludedCertificateRetrievalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificatesExcludedCertificateRetrievalResponse{}

// CertificatesExcludedCertificateRetrievalResponse struct for CertificatesExcludedCertificateRetrievalResponse
type CertificatesExcludedCertificateRetrievalResponse struct {
	Id                    *int32         `json:"Id,omitempty"`
	CertificateThumbprint NullableString `json:"CertificateThumbprint,omitempty"`
	IssuedCN              NullableString `json:"IssuedCN,omitempty"`
	ExcludingUser         NullableString `json:"ExcludingUser,omitempty"`
	DateExcluded          *time.Time     `json:"DateExcluded,omitempty"`
}

// NewCertificatesExcludedCertificateRetrievalResponse instantiates a new CertificatesExcludedCertificateRetrievalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificatesExcludedCertificateRetrievalResponse() *CertificatesExcludedCertificateRetrievalResponse {
	this := CertificatesExcludedCertificateRetrievalResponse{}
	return &this
}

// NewCertificatesExcludedCertificateRetrievalResponseWithDefaults instantiates a new CertificatesExcludedCertificateRetrievalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificatesExcludedCertificateRetrievalResponseWithDefaults() *CertificatesExcludedCertificateRetrievalResponse {
	this := CertificatesExcludedCertificateRetrievalResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CertificatesExcludedCertificateRetrievalResponse) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificatesExcludedCertificateRetrievalResponse) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CertificatesExcludedCertificateRetrievalResponse) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CertificatesExcludedCertificateRetrievalResponse) SetId(v int32) {
	o.Id = &v
}

// GetCertificateThumbprint returns the CertificateThumbprint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificatesExcludedCertificateRetrievalResponse) GetCertificateThumbprint() string {
	if o == nil || isNil(o.CertificateThumbprint.Get()) {
		var ret string
		return ret
	}
	return *o.CertificateThumbprint.Get()
}

// GetCertificateThumbprintOk returns a tuple with the CertificateThumbprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificatesExcludedCertificateRetrievalResponse) GetCertificateThumbprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertificateThumbprint.Get(), o.CertificateThumbprint.IsSet()
}

// HasCertificateThumbprint returns a boolean if a field has been set.
func (o *CertificatesExcludedCertificateRetrievalResponse) HasCertificateThumbprint() bool {
	if o != nil && o.CertificateThumbprint.IsSet() {
		return true
	}

	return false
}

// SetCertificateThumbprint gets a reference to the given NullableString and assigns it to the CertificateThumbprint field.
func (o *CertificatesExcludedCertificateRetrievalResponse) SetCertificateThumbprint(v string) {
	o.CertificateThumbprint.Set(&v)
}

// SetCertificateThumbprintNil sets the value for CertificateThumbprint to be an explicit nil
func (o *CertificatesExcludedCertificateRetrievalResponse) SetCertificateThumbprintNil() {
	o.CertificateThumbprint.Set(nil)
}

// UnsetCertificateThumbprint ensures that no value is present for CertificateThumbprint, not even an explicit nil
func (o *CertificatesExcludedCertificateRetrievalResponse) UnsetCertificateThumbprint() {
	o.CertificateThumbprint.Unset()
}

// GetIssuedCN returns the IssuedCN field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificatesExcludedCertificateRetrievalResponse) GetIssuedCN() string {
	if o == nil || isNil(o.IssuedCN.Get()) {
		var ret string
		return ret
	}
	return *o.IssuedCN.Get()
}

// GetIssuedCNOk returns a tuple with the IssuedCN field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificatesExcludedCertificateRetrievalResponse) GetIssuedCNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IssuedCN.Get(), o.IssuedCN.IsSet()
}

// HasIssuedCN returns a boolean if a field has been set.
func (o *CertificatesExcludedCertificateRetrievalResponse) HasIssuedCN() bool {
	if o != nil && o.IssuedCN.IsSet() {
		return true
	}

	return false
}

// SetIssuedCN gets a reference to the given NullableString and assigns it to the IssuedCN field.
func (o *CertificatesExcludedCertificateRetrievalResponse) SetIssuedCN(v string) {
	o.IssuedCN.Set(&v)
}

// SetIssuedCNNil sets the value for IssuedCN to be an explicit nil
func (o *CertificatesExcludedCertificateRetrievalResponse) SetIssuedCNNil() {
	o.IssuedCN.Set(nil)
}

// UnsetIssuedCN ensures that no value is present for IssuedCN, not even an explicit nil
func (o *CertificatesExcludedCertificateRetrievalResponse) UnsetIssuedCN() {
	o.IssuedCN.Unset()
}

// GetExcludingUser returns the ExcludingUser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CertificatesExcludedCertificateRetrievalResponse) GetExcludingUser() string {
	if o == nil || isNil(o.ExcludingUser.Get()) {
		var ret string
		return ret
	}
	return *o.ExcludingUser.Get()
}

// GetExcludingUserOk returns a tuple with the ExcludingUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CertificatesExcludedCertificateRetrievalResponse) GetExcludingUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExcludingUser.Get(), o.ExcludingUser.IsSet()
}

// HasExcludingUser returns a boolean if a field has been set.
func (o *CertificatesExcludedCertificateRetrievalResponse) HasExcludingUser() bool {
	if o != nil && o.ExcludingUser.IsSet() {
		return true
	}

	return false
}

// SetExcludingUser gets a reference to the given NullableString and assigns it to the ExcludingUser field.
func (o *CertificatesExcludedCertificateRetrievalResponse) SetExcludingUser(v string) {
	o.ExcludingUser.Set(&v)
}

// SetExcludingUserNil sets the value for ExcludingUser to be an explicit nil
func (o *CertificatesExcludedCertificateRetrievalResponse) SetExcludingUserNil() {
	o.ExcludingUser.Set(nil)
}

// UnsetExcludingUser ensures that no value is present for ExcludingUser, not even an explicit nil
func (o *CertificatesExcludedCertificateRetrievalResponse) UnsetExcludingUser() {
	o.ExcludingUser.Unset()
}

// GetDateExcluded returns the DateExcluded field value if set, zero value otherwise.
func (o *CertificatesExcludedCertificateRetrievalResponse) GetDateExcluded() time.Time {
	if o == nil || isNil(o.DateExcluded) {
		var ret time.Time
		return ret
	}
	return *o.DateExcluded
}

// GetDateExcludedOk returns a tuple with the DateExcluded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificatesExcludedCertificateRetrievalResponse) GetDateExcludedOk() (*time.Time, bool) {
	if o == nil || isNil(o.DateExcluded) {
		return nil, false
	}
	return o.DateExcluded, true
}

// HasDateExcluded returns a boolean if a field has been set.
func (o *CertificatesExcludedCertificateRetrievalResponse) HasDateExcluded() bool {
	if o != nil && !isNil(o.DateExcluded) {
		return true
	}

	return false
}

// SetDateExcluded gets a reference to the given time.Time and assigns it to the DateExcluded field.
func (o *CertificatesExcludedCertificateRetrievalResponse) SetDateExcluded(v time.Time) {
	o.DateExcluded = &v
}

func (o CertificatesExcludedCertificateRetrievalResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificatesExcludedCertificateRetrievalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if o.CertificateThumbprint.IsSet() {
		toSerialize["CertificateThumbprint"] = o.CertificateThumbprint.Get()
	}
	if o.IssuedCN.IsSet() {
		toSerialize["IssuedCN"] = o.IssuedCN.Get()
	}
	if o.ExcludingUser.IsSet() {
		toSerialize["ExcludingUser"] = o.ExcludingUser.Get()
	}
	if !isNil(o.DateExcluded) {
		toSerialize["DateExcluded"] = o.DateExcluded
	}
	return toSerialize, nil
}

type NullableCertificatesExcludedCertificateRetrievalResponse struct {
	value *CertificatesExcludedCertificateRetrievalResponse
	isSet bool
}

func (v NullableCertificatesExcludedCertificateRetrievalResponse) Get() *CertificatesExcludedCertificateRetrievalResponse {
	return v.value
}

func (v *NullableCertificatesExcludedCertificateRetrievalResponse) Set(val *CertificatesExcludedCertificateRetrievalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificatesExcludedCertificateRetrievalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificatesExcludedCertificateRetrievalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificatesExcludedCertificateRetrievalResponse(val *CertificatesExcludedCertificateRetrievalResponse) *NullableCertificatesExcludedCertificateRetrievalResponse {
	return &NullableCertificatesExcludedCertificateRetrievalResponse{value: val, isSet: true}
}

func (v NullableCertificatesExcludedCertificateRetrievalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificatesExcludedCertificateRetrievalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
