/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the OrchestratorsJobTypesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrchestratorsJobTypesResponse{}

// OrchestratorsJobTypesResponse struct for OrchestratorsJobTypesResponse
type OrchestratorsJobTypesResponse struct {
	Name                   NullableString `json:"Name,omitempty"`
	CertStoreTypeShortName NullableString `json:"CertStoreTypeShortName,omitempty"`
	CertStoreJobType       NullableString `json:"CertStoreJobType,omitempty"`
	JobTypeId              *string        `json:"JobTypeId,omitempty"`
}

// NewOrchestratorsJobTypesResponse instantiates a new OrchestratorsJobTypesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrchestratorsJobTypesResponse() *OrchestratorsJobTypesResponse {
	this := OrchestratorsJobTypesResponse{}
	return &this
}

// NewOrchestratorsJobTypesResponseWithDefaults instantiates a new OrchestratorsJobTypesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrchestratorsJobTypesResponseWithDefaults() *OrchestratorsJobTypesResponse {
	this := OrchestratorsJobTypesResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrchestratorsJobTypesResponse) GetName() string {
	if o == nil || isNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrchestratorsJobTypesResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *OrchestratorsJobTypesResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *OrchestratorsJobTypesResponse) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *OrchestratorsJobTypesResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *OrchestratorsJobTypesResponse) UnsetName() {
	o.Name.Unset()
}

// GetCertStoreTypeShortName returns the CertStoreTypeShortName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrchestratorsJobTypesResponse) GetCertStoreTypeShortName() string {
	if o == nil || isNil(o.CertStoreTypeShortName.Get()) {
		var ret string
		return ret
	}
	return *o.CertStoreTypeShortName.Get()
}

// GetCertStoreTypeShortNameOk returns a tuple with the CertStoreTypeShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrchestratorsJobTypesResponse) GetCertStoreTypeShortNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertStoreTypeShortName.Get(), o.CertStoreTypeShortName.IsSet()
}

// HasCertStoreTypeShortName returns a boolean if a field has been set.
func (o *OrchestratorsJobTypesResponse) HasCertStoreTypeShortName() bool {
	if o != nil && o.CertStoreTypeShortName.IsSet() {
		return true
	}

	return false
}

// SetCertStoreTypeShortName gets a reference to the given NullableString and assigns it to the CertStoreTypeShortName field.
func (o *OrchestratorsJobTypesResponse) SetCertStoreTypeShortName(v string) {
	o.CertStoreTypeShortName.Set(&v)
}

// SetCertStoreTypeShortNameNil sets the value for CertStoreTypeShortName to be an explicit nil
func (o *OrchestratorsJobTypesResponse) SetCertStoreTypeShortNameNil() {
	o.CertStoreTypeShortName.Set(nil)
}

// UnsetCertStoreTypeShortName ensures that no value is present for CertStoreTypeShortName, not even an explicit nil
func (o *OrchestratorsJobTypesResponse) UnsetCertStoreTypeShortName() {
	o.CertStoreTypeShortName.Unset()
}

// GetCertStoreJobType returns the CertStoreJobType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrchestratorsJobTypesResponse) GetCertStoreJobType() string {
	if o == nil || isNil(o.CertStoreJobType.Get()) {
		var ret string
		return ret
	}
	return *o.CertStoreJobType.Get()
}

// GetCertStoreJobTypeOk returns a tuple with the CertStoreJobType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrchestratorsJobTypesResponse) GetCertStoreJobTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertStoreJobType.Get(), o.CertStoreJobType.IsSet()
}

// HasCertStoreJobType returns a boolean if a field has been set.
func (o *OrchestratorsJobTypesResponse) HasCertStoreJobType() bool {
	if o != nil && o.CertStoreJobType.IsSet() {
		return true
	}

	return false
}

// SetCertStoreJobType gets a reference to the given NullableString and assigns it to the CertStoreJobType field.
func (o *OrchestratorsJobTypesResponse) SetCertStoreJobType(v string) {
	o.CertStoreJobType.Set(&v)
}

// SetCertStoreJobTypeNil sets the value for CertStoreJobType to be an explicit nil
func (o *OrchestratorsJobTypesResponse) SetCertStoreJobTypeNil() {
	o.CertStoreJobType.Set(nil)
}

// UnsetCertStoreJobType ensures that no value is present for CertStoreJobType, not even an explicit nil
func (o *OrchestratorsJobTypesResponse) UnsetCertStoreJobType() {
	o.CertStoreJobType.Unset()
}

// GetJobTypeId returns the JobTypeId field value if set, zero value otherwise.
func (o *OrchestratorsJobTypesResponse) GetJobTypeId() string {
	if o == nil || isNil(o.JobTypeId) {
		var ret string
		return ret
	}
	return *o.JobTypeId
}

// GetJobTypeIdOk returns a tuple with the JobTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrchestratorsJobTypesResponse) GetJobTypeIdOk() (*string, bool) {
	if o == nil || isNil(o.JobTypeId) {
		return nil, false
	}
	return o.JobTypeId, true
}

// HasJobTypeId returns a boolean if a field has been set.
func (o *OrchestratorsJobTypesResponse) HasJobTypeId() bool {
	if o != nil && !isNil(o.JobTypeId) {
		return true
	}

	return false
}

// SetJobTypeId gets a reference to the given string and assigns it to the JobTypeId field.
func (o *OrchestratorsJobTypesResponse) SetJobTypeId(v string) {
	o.JobTypeId = &v
}

func (o OrchestratorsJobTypesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrchestratorsJobTypesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["Name"] = o.Name.Get()
	}
	if o.CertStoreTypeShortName.IsSet() {
		toSerialize["CertStoreTypeShortName"] = o.CertStoreTypeShortName.Get()
	}
	if o.CertStoreJobType.IsSet() {
		toSerialize["CertStoreJobType"] = o.CertStoreJobType.Get()
	}
	if !isNil(o.JobTypeId) {
		toSerialize["JobTypeId"] = o.JobTypeId
	}
	return toSerialize, nil
}

type NullableOrchestratorsJobTypesResponse struct {
	value *OrchestratorsJobTypesResponse
	isSet bool
}

func (v NullableOrchestratorsJobTypesResponse) Get() *OrchestratorsJobTypesResponse {
	return v.value
}

func (v *NullableOrchestratorsJobTypesResponse) Set(val *OrchestratorsJobTypesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrchestratorsJobTypesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrchestratorsJobTypesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrchestratorsJobTypesResponse(val *OrchestratorsJobTypesResponse) *NullableOrchestratorsJobTypesResponse {
	return &NullableOrchestratorsJobTypesResponse{value: val, isSet: true}
}

func (v NullableOrchestratorsJobTypesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrchestratorsJobTypesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
