/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the EnrollmentPatternsEnrollmentPatternFieldRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnrollmentPatternsEnrollmentPatternFieldRequest{}

// EnrollmentPatternsEnrollmentPatternFieldRequest struct for EnrollmentPatternsEnrollmentPatternFieldRequest
type EnrollmentPatternsEnrollmentPatternFieldRequest struct {
	Name     NullableString `json:"Name,omitempty"`
	DataType *int32         `json:"DataType,omitempty"`
	Options  []string       `json:"Options,omitempty"`
}

// NewEnrollmentPatternsEnrollmentPatternFieldRequest instantiates a new EnrollmentPatternsEnrollmentPatternFieldRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrollmentPatternsEnrollmentPatternFieldRequest() *EnrollmentPatternsEnrollmentPatternFieldRequest {
	this := EnrollmentPatternsEnrollmentPatternFieldRequest{}
	return &this
}

// NewEnrollmentPatternsEnrollmentPatternFieldRequestWithDefaults instantiates a new EnrollmentPatternsEnrollmentPatternFieldRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrollmentPatternsEnrollmentPatternFieldRequestWithDefaults() *EnrollmentPatternsEnrollmentPatternFieldRequest {
	this := EnrollmentPatternsEnrollmentPatternFieldRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) GetName() string {
	if o == nil || isNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) UnsetName() {
	o.Name.Unset()
}

// GetDataType returns the DataType field value if set, zero value otherwise.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) GetDataType() int32 {
	if o == nil || isNil(o.DataType) {
		var ret int32
		return ret
	}
	return *o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) GetDataTypeOk() (*int32, bool) {
	if o == nil || isNil(o.DataType) {
		return nil, false
	}
	return o.DataType, true
}

// HasDataType returns a boolean if a field has been set.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) HasDataType() bool {
	if o != nil && !isNil(o.DataType) {
		return true
	}

	return false
}

// SetDataType gets a reference to the given int32 and assigns it to the DataType field.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) SetDataType(v int32) {
	o.DataType = &v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) GetOptionsOk() ([]string, bool) {
	if o == nil || isNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) HasOptions() bool {
	if o != nil && isNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []string and assigns it to the Options field.
func (o *EnrollmentPatternsEnrollmentPatternFieldRequest) SetOptions(v []string) {
	o.Options = v
}

func (o EnrollmentPatternsEnrollmentPatternFieldRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnrollmentPatternsEnrollmentPatternFieldRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["Name"] = o.Name.Get()
	}
	if !isNil(o.DataType) {
		toSerialize["DataType"] = o.DataType
	}
	if o.Options != nil {
		toSerialize["Options"] = o.Options
	}
	return toSerialize, nil
}

type NullableEnrollmentPatternsEnrollmentPatternFieldRequest struct {
	value *EnrollmentPatternsEnrollmentPatternFieldRequest
	isSet bool
}

func (v NullableEnrollmentPatternsEnrollmentPatternFieldRequest) Get() *EnrollmentPatternsEnrollmentPatternFieldRequest {
	return v.value
}

func (v *NullableEnrollmentPatternsEnrollmentPatternFieldRequest) Set(val *EnrollmentPatternsEnrollmentPatternFieldRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrollmentPatternsEnrollmentPatternFieldRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrollmentPatternsEnrollmentPatternFieldRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrollmentPatternsEnrollmentPatternFieldRequest(val *EnrollmentPatternsEnrollmentPatternFieldRequest) *NullableEnrollmentPatternsEnrollmentPatternFieldRequest {
	return &NullableEnrollmentPatternsEnrollmentPatternFieldRequest{value: val, isSet: true}
}

func (v NullableEnrollmentPatternsEnrollmentPatternFieldRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrollmentPatternsEnrollmentPatternFieldRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
