/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the WorkflowsSignalConfigurationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowsSignalConfigurationRequest{}

// WorkflowsSignalConfigurationRequest struct for WorkflowsSignalConfigurationRequest
type WorkflowsSignalConfigurationRequest struct {
	// The name of the signal.
	SignalName NullableString `json:"SignalName,omitempty"`
	// The roles that are allowed to send the signal.
	RoleIds []int32 `json:"RoleIds,omitempty"`
}

// NewWorkflowsSignalConfigurationRequest instantiates a new WorkflowsSignalConfigurationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowsSignalConfigurationRequest() *WorkflowsSignalConfigurationRequest {
	this := WorkflowsSignalConfigurationRequest{}
	return &this
}

// NewWorkflowsSignalConfigurationRequestWithDefaults instantiates a new WorkflowsSignalConfigurationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowsSignalConfigurationRequestWithDefaults() *WorkflowsSignalConfigurationRequest {
	this := WorkflowsSignalConfigurationRequest{}
	return &this
}

// GetSignalName returns the SignalName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowsSignalConfigurationRequest) GetSignalName() string {
	if o == nil || isNil(o.SignalName.Get()) {
		var ret string
		return ret
	}
	return *o.SignalName.Get()
}

// GetSignalNameOk returns a tuple with the SignalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowsSignalConfigurationRequest) GetSignalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignalName.Get(), o.SignalName.IsSet()
}

// HasSignalName returns a boolean if a field has been set.
func (o *WorkflowsSignalConfigurationRequest) HasSignalName() bool {
	if o != nil && o.SignalName.IsSet() {
		return true
	}

	return false
}

// SetSignalName gets a reference to the given NullableString and assigns it to the SignalName field.
func (o *WorkflowsSignalConfigurationRequest) SetSignalName(v string) {
	o.SignalName.Set(&v)
}

// SetSignalNameNil sets the value for SignalName to be an explicit nil
func (o *WorkflowsSignalConfigurationRequest) SetSignalNameNil() {
	o.SignalName.Set(nil)
}

// UnsetSignalName ensures that no value is present for SignalName, not even an explicit nil
func (o *WorkflowsSignalConfigurationRequest) UnsetSignalName() {
	o.SignalName.Unset()
}

// GetRoleIds returns the RoleIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowsSignalConfigurationRequest) GetRoleIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.RoleIds
}

// GetRoleIdsOk returns a tuple with the RoleIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowsSignalConfigurationRequest) GetRoleIdsOk() ([]int32, bool) {
	if o == nil || isNil(o.RoleIds) {
		return nil, false
	}
	return o.RoleIds, true
}

// HasRoleIds returns a boolean if a field has been set.
func (o *WorkflowsSignalConfigurationRequest) HasRoleIds() bool {
	if o != nil && isNil(o.RoleIds) {
		return true
	}

	return false
}

// SetRoleIds gets a reference to the given []int32 and assigns it to the RoleIds field.
func (o *WorkflowsSignalConfigurationRequest) SetRoleIds(v []int32) {
	o.RoleIds = v
}

func (o WorkflowsSignalConfigurationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowsSignalConfigurationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SignalName.IsSet() {
		toSerialize["SignalName"] = o.SignalName.Get()
	}
	if o.RoleIds != nil {
		toSerialize["RoleIds"] = o.RoleIds
	}
	return toSerialize, nil
}

type NullableWorkflowsSignalConfigurationRequest struct {
	value *WorkflowsSignalConfigurationRequest
	isSet bool
}

func (v NullableWorkflowsSignalConfigurationRequest) Get() *WorkflowsSignalConfigurationRequest {
	return v.value
}

func (v *NullableWorkflowsSignalConfigurationRequest) Set(val *WorkflowsSignalConfigurationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowsSignalConfigurationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowsSignalConfigurationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowsSignalConfigurationRequest(val *WorkflowsSignalConfigurationRequest) *NullableWorkflowsSignalConfigurationRequest {
	return &NullableWorkflowsSignalConfigurationRequest{value: val, isSet: true}
}

func (v NullableWorkflowsSignalConfigurationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowsSignalConfigurationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
