/*
Copyright 2026 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CertificateStoresTypesPasswordOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateStoresTypesPasswordOptions{}

// CertificateStoresTypesPasswordOptions struct for CertificateStoresTypesPasswordOptions
type CertificateStoresTypesPasswordOptions struct {
	EntrySupported *bool                                             `json:"EntrySupported,omitempty"`
	StoreRequired  *bool                                             `json:"StoreRequired,omitempty"`
	Style          *CSSCMSDataModelEnumsCertStoreTypesPasswordStyles `json:"Style,omitempty"`
}

// NewCertificateStoresTypesPasswordOptions instantiates a new CertificateStoresTypesPasswordOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateStoresTypesPasswordOptions() *CertificateStoresTypesPasswordOptions {
	this := CertificateStoresTypesPasswordOptions{}
	return &this
}

// NewCertificateStoresTypesPasswordOptionsWithDefaults instantiates a new CertificateStoresTypesPasswordOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateStoresTypesPasswordOptionsWithDefaults() *CertificateStoresTypesPasswordOptions {
	this := CertificateStoresTypesPasswordOptions{}
	return &this
}

// GetEntrySupported returns the EntrySupported field value if set, zero value otherwise.
func (o *CertificateStoresTypesPasswordOptions) GetEntrySupported() bool {
	if o == nil || isNil(o.EntrySupported) {
		var ret bool
		return ret
	}
	return *o.EntrySupported
}

// GetEntrySupportedOk returns a tuple with the EntrySupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesPasswordOptions) GetEntrySupportedOk() (*bool, bool) {
	if o == nil || isNil(o.EntrySupported) {
		return nil, false
	}
	return o.EntrySupported, true
}

// HasEntrySupported returns a boolean if a field has been set.
func (o *CertificateStoresTypesPasswordOptions) HasEntrySupported() bool {
	if o != nil && !isNil(o.EntrySupported) {
		return true
	}

	return false
}

// SetEntrySupported gets a reference to the given bool and assigns it to the EntrySupported field.
func (o *CertificateStoresTypesPasswordOptions) SetEntrySupported(v bool) {
	o.EntrySupported = &v
}

// GetStoreRequired returns the StoreRequired field value if set, zero value otherwise.
func (o *CertificateStoresTypesPasswordOptions) GetStoreRequired() bool {
	if o == nil || isNil(o.StoreRequired) {
		var ret bool
		return ret
	}
	return *o.StoreRequired
}

// GetStoreRequiredOk returns a tuple with the StoreRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesPasswordOptions) GetStoreRequiredOk() (*bool, bool) {
	if o == nil || isNil(o.StoreRequired) {
		return nil, false
	}
	return o.StoreRequired, true
}

// HasStoreRequired returns a boolean if a field has been set.
func (o *CertificateStoresTypesPasswordOptions) HasStoreRequired() bool {
	if o != nil && !isNil(o.StoreRequired) {
		return true
	}

	return false
}

// SetStoreRequired gets a reference to the given bool and assigns it to the StoreRequired field.
func (o *CertificateStoresTypesPasswordOptions) SetStoreRequired(v bool) {
	o.StoreRequired = &v
}

// GetStyle returns the Style field value if set, zero value otherwise.
func (o *CertificateStoresTypesPasswordOptions) GetStyle() CSSCMSDataModelEnumsCertStoreTypesPasswordStyles {
	if o == nil || isNil(o.Style) {
		var ret CSSCMSDataModelEnumsCertStoreTypesPasswordStyles
		return ret
	}
	return *o.Style
}

// GetStyleOk returns a tuple with the Style field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateStoresTypesPasswordOptions) GetStyleOk() (*CSSCMSDataModelEnumsCertStoreTypesPasswordStyles, bool) {
	if o == nil || isNil(o.Style) {
		return nil, false
	}
	return o.Style, true
}

// HasStyle returns a boolean if a field has been set.
func (o *CertificateStoresTypesPasswordOptions) HasStyle() bool {
	if o != nil && !isNil(o.Style) {
		return true
	}

	return false
}

// SetStyle gets a reference to the given CSSCMSDataModelEnumsCertStoreTypesPasswordStyles and assigns it to the Style field.
func (o *CertificateStoresTypesPasswordOptions) SetStyle(v CSSCMSDataModelEnumsCertStoreTypesPasswordStyles) {
	o.Style = &v
}

func (o CertificateStoresTypesPasswordOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateStoresTypesPasswordOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.EntrySupported) {
		toSerialize["EntrySupported"] = o.EntrySupported
	}
	if !isNil(o.StoreRequired) {
		toSerialize["StoreRequired"] = o.StoreRequired
	}
	if !isNil(o.Style) {
		toSerialize["Style"] = o.Style
	}
	return toSerialize, nil
}

type NullableCertificateStoresTypesPasswordOptions struct {
	value *CertificateStoresTypesPasswordOptions
	isSet bool
}

func (v NullableCertificateStoresTypesPasswordOptions) Get() *CertificateStoresTypesPasswordOptions {
	return v.value
}

func (v *NullableCertificateStoresTypesPasswordOptions) Set(val *CertificateStoresTypesPasswordOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateStoresTypesPasswordOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateStoresTypesPasswordOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateStoresTypesPasswordOptions(val *CertificateStoresTypesPasswordOptions) *NullableCertificateStoresTypesPasswordOptions {
	return &NullableCertificateStoresTypesPasswordOptions{value: val, isSet: true}
}

func (v NullableCertificateStoresTypesPasswordOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateStoresTypesPasswordOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
