/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 24.4.2

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CSSCMSDataModelModelsSecurityCertificatePermissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CSSCMSDataModelModelsSecurityCertificatePermissions{}

// CSSCMSDataModelModelsSecurityCertificatePermissions struct for CSSCMSDataModelModelsSecurityCertificatePermissions
type CSSCMSDataModelModelsSecurityCertificatePermissions struct {
	Roles []CSSCMSDataModelModelsSecuritySecurityRolesSecurityRoleResponseBase `json:"Roles,omitempty"`
}

// NewCSSCMSDataModelModelsSecurityCertificatePermissions instantiates a new CSSCMSDataModelModelsSecurityCertificatePermissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSSCMSDataModelModelsSecurityCertificatePermissions() *CSSCMSDataModelModelsSecurityCertificatePermissions {
	this := CSSCMSDataModelModelsSecurityCertificatePermissions{}
	return &this
}

// NewCSSCMSDataModelModelsSecurityCertificatePermissionsWithDefaults instantiates a new CSSCMSDataModelModelsSecurityCertificatePermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSSCMSDataModelModelsSecurityCertificatePermissionsWithDefaults() *CSSCMSDataModelModelsSecurityCertificatePermissions {
	this := CSSCMSDataModelModelsSecurityCertificatePermissions{}
	return &this
}

// GetRoles returns the Roles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsSecurityCertificatePermissions) GetRoles() []CSSCMSDataModelModelsSecuritySecurityRolesSecurityRoleResponseBase {
	if o == nil {
		var ret []CSSCMSDataModelModelsSecuritySecurityRolesSecurityRoleResponseBase
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsSecurityCertificatePermissions) GetRolesOk() ([]CSSCMSDataModelModelsSecuritySecurityRolesSecurityRoleResponseBase, bool) {
	if o == nil || isNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsSecurityCertificatePermissions) HasRoles() bool {
	if o != nil && isNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []CSSCMSDataModelModelsSecuritySecurityRolesSecurityRoleResponseBase and assigns it to the Roles field.
func (o *CSSCMSDataModelModelsSecurityCertificatePermissions) SetRoles(v []CSSCMSDataModelModelsSecuritySecurityRolesSecurityRoleResponseBase) {
	o.Roles = v
}

func (o CSSCMSDataModelModelsSecurityCertificatePermissions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CSSCMSDataModelModelsSecurityCertificatePermissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Roles != nil {
		toSerialize["Roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableCSSCMSDataModelModelsSecurityCertificatePermissions struct {
	value *CSSCMSDataModelModelsSecurityCertificatePermissions
	isSet bool
}

func (v NullableCSSCMSDataModelModelsSecurityCertificatePermissions) Get() *CSSCMSDataModelModelsSecurityCertificatePermissions {
	return v.value
}

func (v *NullableCSSCMSDataModelModelsSecurityCertificatePermissions) Set(val *CSSCMSDataModelModelsSecurityCertificatePermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSDataModelModelsSecurityCertificatePermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSDataModelModelsSecurityCertificatePermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSDataModelModelsSecurityCertificatePermissions(val *CSSCMSDataModelModelsSecurityCertificatePermissions) *NullableCSSCMSDataModelModelsSecurityCertificatePermissions {
	return &NullableCSSCMSDataModelModelsSecurityCertificatePermissions{value: val, isSet: true}
}

func (v NullableCSSCMSDataModelModelsSecurityCertificatePermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSDataModelModelsSecurityCertificatePermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
