/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 24.4.2

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// checks if the CSSCMSDataModelModelsEnrollmentRenewalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CSSCMSDataModelModelsEnrollmentRenewalRequest{}

// CSSCMSDataModelModelsEnrollmentRenewalRequest struct for CSSCMSDataModelModelsEnrollmentRenewalRequest
type CSSCMSDataModelModelsEnrollmentRenewalRequest struct {
	CertificateId        NullableInt32  `json:"CertificateId,omitempty"`
	Thumbprint           NullableString `json:"Thumbprint,omitempty"`
	CertificateAuthority NullableString `json:"CertificateAuthority,omitempty"`
	Template             NullableString `json:"Template,omitempty"`
	Timestamp            *time.Time     `json:"Timestamp,omitempty"`
}

// NewCSSCMSDataModelModelsEnrollmentRenewalRequest instantiates a new CSSCMSDataModelModelsEnrollmentRenewalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSSCMSDataModelModelsEnrollmentRenewalRequest() *CSSCMSDataModelModelsEnrollmentRenewalRequest {
	this := CSSCMSDataModelModelsEnrollmentRenewalRequest{}
	return &this
}

// NewCSSCMSDataModelModelsEnrollmentRenewalRequestWithDefaults instantiates a new CSSCMSDataModelModelsEnrollmentRenewalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSSCMSDataModelModelsEnrollmentRenewalRequestWithDefaults() *CSSCMSDataModelModelsEnrollmentRenewalRequest {
	this := CSSCMSDataModelModelsEnrollmentRenewalRequest{}
	return &this
}

// GetCertificateId returns the CertificateId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetCertificateId() int32 {
	if o == nil || isNil(o.CertificateId.Get()) {
		var ret int32
		return ret
	}
	return *o.CertificateId.Get()
}

// GetCertificateIdOk returns a tuple with the CertificateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetCertificateIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertificateId.Get(), o.CertificateId.IsSet()
}

// HasCertificateId returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) HasCertificateId() bool {
	if o != nil && o.CertificateId.IsSet() {
		return true
	}

	return false
}

// SetCertificateId gets a reference to the given NullableInt32 and assigns it to the CertificateId field.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetCertificateId(v int32) {
	o.CertificateId.Set(&v)
}

// SetCertificateIdNil sets the value for CertificateId to be an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetCertificateIdNil() {
	o.CertificateId.Set(nil)
}

// UnsetCertificateId ensures that no value is present for CertificateId, not even an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) UnsetCertificateId() {
	o.CertificateId.Unset()
}

// GetThumbprint returns the Thumbprint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetThumbprint() string {
	if o == nil || isNil(o.Thumbprint.Get()) {
		var ret string
		return ret
	}
	return *o.Thumbprint.Get()
}

// GetThumbprintOk returns a tuple with the Thumbprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetThumbprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Thumbprint.Get(), o.Thumbprint.IsSet()
}

// HasThumbprint returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) HasThumbprint() bool {
	if o != nil && o.Thumbprint.IsSet() {
		return true
	}

	return false
}

// SetThumbprint gets a reference to the given NullableString and assigns it to the Thumbprint field.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetThumbprint(v string) {
	o.Thumbprint.Set(&v)
}

// SetThumbprintNil sets the value for Thumbprint to be an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetThumbprintNil() {
	o.Thumbprint.Set(nil)
}

// UnsetThumbprint ensures that no value is present for Thumbprint, not even an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) UnsetThumbprint() {
	o.Thumbprint.Unset()
}

// GetCertificateAuthority returns the CertificateAuthority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetCertificateAuthority() string {
	if o == nil || isNil(o.CertificateAuthority.Get()) {
		var ret string
		return ret
	}
	return *o.CertificateAuthority.Get()
}

// GetCertificateAuthorityOk returns a tuple with the CertificateAuthority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetCertificateAuthorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertificateAuthority.Get(), o.CertificateAuthority.IsSet()
}

// HasCertificateAuthority returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) HasCertificateAuthority() bool {
	if o != nil && o.CertificateAuthority.IsSet() {
		return true
	}

	return false
}

// SetCertificateAuthority gets a reference to the given NullableString and assigns it to the CertificateAuthority field.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetCertificateAuthority(v string) {
	o.CertificateAuthority.Set(&v)
}

// SetCertificateAuthorityNil sets the value for CertificateAuthority to be an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetCertificateAuthorityNil() {
	o.CertificateAuthority.Set(nil)
}

// UnsetCertificateAuthority ensures that no value is present for CertificateAuthority, not even an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) UnsetCertificateAuthority() {
	o.CertificateAuthority.Unset()
}

// GetTemplate returns the Template field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetTemplate() string {
	if o == nil || isNil(o.Template.Get()) {
		var ret string
		return ret
	}
	return *o.Template.Get()
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Template.Get(), o.Template.IsSet()
}

// HasTemplate returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) HasTemplate() bool {
	if o != nil && o.Template.IsSet() {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given NullableString and assigns it to the Template field.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetTemplate(v string) {
	o.Template.Set(&v)
}

// SetTemplateNil sets the value for Template to be an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetTemplateNil() {
	o.Template.Set(nil)
}

// UnsetTemplate ensures that no value is present for Template, not even an explicit nil
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) UnsetTemplate() {
	o.Template.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetTimestamp() time.Time {
	if o == nil || isNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil || isNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) HasTimestamp() bool {
	if o != nil && !isNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *CSSCMSDataModelModelsEnrollmentRenewalRequest) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o CSSCMSDataModelModelsEnrollmentRenewalRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CSSCMSDataModelModelsEnrollmentRenewalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CertificateId.IsSet() {
		toSerialize["CertificateId"] = o.CertificateId.Get()
	}
	if o.Thumbprint.IsSet() {
		toSerialize["Thumbprint"] = o.Thumbprint.Get()
	}
	if o.CertificateAuthority.IsSet() {
		toSerialize["CertificateAuthority"] = o.CertificateAuthority.Get()
	}
	if o.Template.IsSet() {
		toSerialize["Template"] = o.Template.Get()
	}
	if !isNil(o.Timestamp) {
		toSerialize["Timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableCSSCMSDataModelModelsEnrollmentRenewalRequest struct {
	value *CSSCMSDataModelModelsEnrollmentRenewalRequest
	isSet bool
}

func (v NullableCSSCMSDataModelModelsEnrollmentRenewalRequest) Get() *CSSCMSDataModelModelsEnrollmentRenewalRequest {
	return v.value
}

func (v *NullableCSSCMSDataModelModelsEnrollmentRenewalRequest) Set(val *CSSCMSDataModelModelsEnrollmentRenewalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSDataModelModelsEnrollmentRenewalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSDataModelModelsEnrollmentRenewalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSDataModelModelsEnrollmentRenewalRequest(val *CSSCMSDataModelModelsEnrollmentRenewalRequest) *NullableCSSCMSDataModelModelsEnrollmentRenewalRequest {
	return &NullableCSSCMSDataModelModelsEnrollmentRenewalRequest{value: val, isSet: true}
}

func (v NullableCSSCMSDataModelModelsEnrollmentRenewalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSDataModelModelsEnrollmentRenewalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
