/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 25.1.1

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"errors"
	"fmt"
)

// CSSCMSCoreEnumsClaimType the model 'CSSCMSCoreEnumsClaimType'
type CSSCMSCoreEnumsClaimType int32

// List of CSS.CMS.Core.Enums.ClaimType
const (
	CSSCMSCOREENUMSCLAIMTYPE_User          CSSCMSCoreEnumsClaimType = 0
	CSSCMSCOREENUMSCLAIMTYPE_Group         CSSCMSCoreEnumsClaimType = 1
	CSSCMSCOREENUMSCLAIMTYPE_Computer      CSSCMSCoreEnumsClaimType = 2
	CSSCMSCOREENUMSCLAIMTYPE_OAuthOid      CSSCMSCoreEnumsClaimType = 3
	CSSCMSCOREENUMSCLAIMTYPE_OAuthRole     CSSCMSCoreEnumsClaimType = 4
	CSSCMSCOREENUMSCLAIMTYPE_OAuthSubject  CSSCMSCoreEnumsClaimType = 5
	CSSCMSCOREENUMSCLAIMTYPE_OAuthClientId CSSCMSCoreEnumsClaimType = 6
)

func ParseCSSCMSCoreEnumsClaimType(s string) (*CSSCMSCoreEnumsClaimType, error) {
	var claimType CSSCMSCoreEnumsClaimType
	err := claimType.Parse(s)
	if err != nil {
		return nil, err
	}
	return &claimType, err
}

func (c *CSSCMSCoreEnumsClaimType) Parse(s string) error {
	var stringsToEnum = map[string]CSSCMSCoreEnumsClaimType{
		"User":          CSSCMSCOREENUMSCLAIMTYPE_User,
		"Group":         CSSCMSCOREENUMSCLAIMTYPE_Group,
		"Computer":      CSSCMSCOREENUMSCLAIMTYPE_Computer,
		"OAuthOid":      CSSCMSCOREENUMSCLAIMTYPE_OAuthOid,
		"OAuthRole":     CSSCMSCOREENUMSCLAIMTYPE_OAuthRole,
		"OAuthSubject":  CSSCMSCOREENUMSCLAIMTYPE_OAuthSubject,
		"OAuthClientId": CSSCMSCOREENUMSCLAIMTYPE_OAuthClientId,
	}

	if val, ok := stringsToEnum[s]; ok {
		*c = val
		return nil
	}
	return errors.New(fmt.Sprintf("Could not map to enum CSSCMSCoreEnumsClaimType. Value: %s ", s))
}

// All allowed values of CSSCMSCoreEnumsClaimType enum
var AllowedCSSCMSCoreEnumsClaimTypeEnumValues = []CSSCMSCoreEnumsClaimType{
	0,
	1,
	2,
	3,
	4,
	5,
	6,
}

func (v *CSSCMSCoreEnumsClaimType) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CSSCMSCoreEnumsClaimType(value)
	for _, existing := range AllowedCSSCMSCoreEnumsClaimTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CSSCMSCoreEnumsClaimType", value)
}

// NewCSSCMSCoreEnumsClaimTypeFromValue returns a pointer to a valid CSSCMSCoreEnumsClaimType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCSSCMSCoreEnumsClaimTypeFromValue(v int32) (*CSSCMSCoreEnumsClaimType, error) {
	ev := CSSCMSCoreEnumsClaimType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CSSCMSCoreEnumsClaimType: valid values are %v", v, AllowedCSSCMSCoreEnumsClaimTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CSSCMSCoreEnumsClaimType) IsValid() bool {
	for _, existing := range AllowedCSSCMSCoreEnumsClaimTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CSS.CMS.Core.Enums.ClaimType value
func (v CSSCMSCoreEnumsClaimType) Ptr() *CSSCMSCoreEnumsClaimType {
	return &v
}

type NullableCSSCMSCoreEnumsClaimType struct {
	value *CSSCMSCoreEnumsClaimType
	isSet bool
}

func (v NullableCSSCMSCoreEnumsClaimType) Get() *CSSCMSCoreEnumsClaimType {
	return v.value
}

func (v *NullableCSSCMSCoreEnumsClaimType) Set(val *CSSCMSCoreEnumsClaimType) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSCoreEnumsClaimType) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSCoreEnumsClaimType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSCoreEnumsClaimType(val *CSSCMSCoreEnumsClaimType) *NullableCSSCMSCoreEnumsClaimType {
	return &NullableCSSCMSCoreEnumsClaimType{value: val, isSet: true}
}

func (v NullableCSSCMSCoreEnumsClaimType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSCoreEnumsClaimType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
