/*

Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

<p>This page provides a utility through which the Keyfactor API endpoints can be called and results returned.                                                           It is intended to be used primarily for validation, testing and workflow development.                                                           It also serves secondarily as documentation for the API.</p>                                                          <p>If you would like to view documentation containing details on the Keyfactor API and endpoints,                                                           please refer to the Web API section of the Keyfactor Command documentation.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package command

import (
	"encoding/json"
)

// checks if the CSSCMSDataModelModelsMetadataSingleUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CSSCMSDataModelModelsMetadataSingleUpdateRequest{}

// CSSCMSDataModelModelsMetadataSingleUpdateRequest struct for CSSCMSDataModelModelsMetadataSingleUpdateRequest
type CSSCMSDataModelModelsMetadataSingleUpdateRequest struct {
	MetadataName      NullableString `json:"metadataName,omitempty"`
	Value             NullableString `json:"value,omitempty"`
	OverwriteExisting *bool          `json:"overwriteExisting,omitempty"`
}

// NewCSSCMSDataModelModelsMetadataSingleUpdateRequest instantiates a new CSSCMSDataModelModelsMetadataSingleUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSSCMSDataModelModelsMetadataSingleUpdateRequest() *CSSCMSDataModelModelsMetadataSingleUpdateRequest {
	this := CSSCMSDataModelModelsMetadataSingleUpdateRequest{}
	return &this
}

// NewCSSCMSDataModelModelsMetadataSingleUpdateRequestWithDefaults instantiates a new CSSCMSDataModelModelsMetadataSingleUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSSCMSDataModelModelsMetadataSingleUpdateRequestWithDefaults() *CSSCMSDataModelModelsMetadataSingleUpdateRequest {
	this := CSSCMSDataModelModelsMetadataSingleUpdateRequest{}
	return &this
}

// GetMetadataName returns the MetadataName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) GetMetadataName() string {
	if o == nil || isNil(o.MetadataName.Get()) {
		var ret string
		return ret
	}
	return *o.MetadataName.Get()
}

// GetMetadataNameOk returns a tuple with the MetadataName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) GetMetadataNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetadataName.Get(), o.MetadataName.IsSet()
}

// HasMetadataName returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) HasMetadataName() bool {
	if o != nil && o.MetadataName.IsSet() {
		return true
	}

	return false
}

// SetMetadataName gets a reference to the given NullableString and assigns it to the MetadataName field.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) SetMetadataName(v string) {
	o.MetadataName.Set(&v)
}

// SetMetadataNameNil sets the value for MetadataName to be an explicit nil
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) SetMetadataNameNil() {
	o.MetadataName.Set(nil)
}

// UnsetMetadataName ensures that no value is present for MetadataName, not even an explicit nil
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) UnsetMetadataName() {
	o.MetadataName.Unset()
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) GetValue() string {
	if o == nil || isNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) SetValue(v string) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) UnsetValue() {
	o.Value.Unset()
}

// GetOverwriteExisting returns the OverwriteExisting field value if set, zero value otherwise.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) GetOverwriteExisting() bool {
	if o == nil || isNil(o.OverwriteExisting) {
		var ret bool
		return ret
	}
	return *o.OverwriteExisting
}

// GetOverwriteExistingOk returns a tuple with the OverwriteExisting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) GetOverwriteExistingOk() (*bool, bool) {
	if o == nil || isNil(o.OverwriteExisting) {
		return nil, false
	}
	return o.OverwriteExisting, true
}

// HasOverwriteExisting returns a boolean if a field has been set.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) HasOverwriteExisting() bool {
	if o != nil && !isNil(o.OverwriteExisting) {
		return true
	}

	return false
}

// SetOverwriteExisting gets a reference to the given bool and assigns it to the OverwriteExisting field.
func (o *CSSCMSDataModelModelsMetadataSingleUpdateRequest) SetOverwriteExisting(v bool) {
	o.OverwriteExisting = &v
}

func (o CSSCMSDataModelModelsMetadataSingleUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CSSCMSDataModelModelsMetadataSingleUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MetadataName.IsSet() {
		toSerialize["metadataName"] = o.MetadataName.Get()
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if !isNil(o.OverwriteExisting) {
		toSerialize["overwriteExisting"] = o.OverwriteExisting
	}
	return toSerialize, nil
}

type NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest struct {
	value *CSSCMSDataModelModelsMetadataSingleUpdateRequest
	isSet bool
}

func (v NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest) Get() *CSSCMSDataModelModelsMetadataSingleUpdateRequest {
	return v.value
}

func (v *NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest) Set(val *CSSCMSDataModelModelsMetadataSingleUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSDataModelModelsMetadataSingleUpdateRequest(val *CSSCMSDataModelModelsMetadataSingleUpdateRequest) *NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest {
	return &NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest{value: val, isSet: true}
}

func (v NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSDataModelModelsMetadataSingleUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
