/*

Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

<p>This page provides a utility through which the Keyfactor API endpoints can be called and results returned.                                                           It is intended to be used primarily for validation, testing and workflow development.                                                           It also serves secondarily as documentation for the API.</p>                                                          <p>If you would like to view documentation containing details on the Keyfactor API and endpoints,                                                           please refer to the Web API section of the Keyfactor Command documentation.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package command

import (
	"encoding/json"
)

// checks if the CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest{}

// CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest struct for CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest
type CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest struct {
	KeyUpdateRequest CSSCMSDataModelModelsSSHKeysKeyUpdateRequest `json:"keyUpdateRequest"`
	Id               int32                                        `json:"id"`
}

// NewCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest instantiates a new CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest(keyUpdateRequest CSSCMSDataModelModelsSSHKeysKeyUpdateRequest, id int32) *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest {
	this := CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest{}
	this.KeyUpdateRequest = keyUpdateRequest
	this.Id = id
	return &this
}

// NewCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequestWithDefaults instantiates a new CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequestWithDefaults() *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest {
	this := CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest{}
	return &this
}

// GetKeyUpdateRequest returns the KeyUpdateRequest field value
func (o *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) GetKeyUpdateRequest() CSSCMSDataModelModelsSSHKeysKeyUpdateRequest {
	if o == nil {
		var ret CSSCMSDataModelModelsSSHKeysKeyUpdateRequest
		return ret
	}

	return o.KeyUpdateRequest
}

// GetKeyUpdateRequestOk returns a tuple with the KeyUpdateRequest field value
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) GetKeyUpdateRequestOk() (*CSSCMSDataModelModelsSSHKeysKeyUpdateRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyUpdateRequest, true
}

// SetKeyUpdateRequest sets field value
func (o *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) SetKeyUpdateRequest(v CSSCMSDataModelModelsSSHKeysKeyUpdateRequest) {
	o.KeyUpdateRequest = v
}

// GetId returns the Id field value
func (o *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) SetId(v int32) {
	o.Id = v
}

func (o CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keyUpdateRequest"] = o.KeyUpdateRequest
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest struct {
	value *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest
	isSet bool
}

func (v NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) Get() *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest {
	return v.value
}

func (v *NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) Set(val *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest(val *CSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) *NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest {
	return &NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest{value: val, isSet: true}
}

func (v NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCSSCMSDataModelModelsSSHServiceAccountsServiceAccountUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
