/*
Copyright 2025 Keyfactor
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
thespecific language governing permissions and limitations under the
License.

This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.

Keyfactor Command Version: 24.4.2

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the WorkflowsSignalDefinitionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowsSignalDefinitionResponse{}

// WorkflowsSignalDefinitionResponse struct for WorkflowsSignalDefinitionResponse
type WorkflowsSignalDefinitionResponse struct {
	InputParameters map[string]WorkflowsParameterDefinitionResponse `json:"InputParameters,omitempty"`
}

// NewWorkflowsSignalDefinitionResponse instantiates a new WorkflowsSignalDefinitionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowsSignalDefinitionResponse() *WorkflowsSignalDefinitionResponse {
	this := WorkflowsSignalDefinitionResponse{}
	return &this
}

// NewWorkflowsSignalDefinitionResponseWithDefaults instantiates a new WorkflowsSignalDefinitionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowsSignalDefinitionResponseWithDefaults() *WorkflowsSignalDefinitionResponse {
	this := WorkflowsSignalDefinitionResponse{}
	return &this
}

// GetInputParameters returns the InputParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowsSignalDefinitionResponse) GetInputParameters() map[string]WorkflowsParameterDefinitionResponse {
	if o == nil {
		var ret map[string]WorkflowsParameterDefinitionResponse
		return ret
	}
	return o.InputParameters
}

// GetInputParametersOk returns a tuple with the InputParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowsSignalDefinitionResponse) GetInputParametersOk() (*map[string]WorkflowsParameterDefinitionResponse, bool) {
	if o == nil || isNil(o.InputParameters) {
		return nil, false
	}
	return &o.InputParameters, true
}

// HasInputParameters returns a boolean if a field has been set.
func (o *WorkflowsSignalDefinitionResponse) HasInputParameters() bool {
	if o != nil && isNil(o.InputParameters) {
		return true
	}

	return false
}

// SetInputParameters gets a reference to the given map[string]WorkflowsParameterDefinitionResponse and assigns it to the InputParameters field.
func (o *WorkflowsSignalDefinitionResponse) SetInputParameters(v map[string]WorkflowsParameterDefinitionResponse) {
	o.InputParameters = v
}

func (o WorkflowsSignalDefinitionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowsSignalDefinitionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.InputParameters != nil {
		toSerialize["InputParameters"] = o.InputParameters
	}
	return toSerialize, nil
}

type NullableWorkflowsSignalDefinitionResponse struct {
	value *WorkflowsSignalDefinitionResponse
	isSet bool
}

func (v NullableWorkflowsSignalDefinitionResponse) Get() *WorkflowsSignalDefinitionResponse {
	return v.value
}

func (v *NullableWorkflowsSignalDefinitionResponse) Set(val *WorkflowsSignalDefinitionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowsSignalDefinitionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowsSignalDefinitionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowsSignalDefinitionResponse(val *WorkflowsSignalDefinitionResponse) *NullableWorkflowsSignalDefinitionResponse {
	return &NullableWorkflowsSignalDefinitionResponse{value: val, isSet: true}
}

func (v NullableWorkflowsSignalDefinitionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowsSignalDefinitionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
