/*
Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

Testing ServerApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package command

import (
	"context"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_command_ServerApiService(t *testing.T) {

	cwd, _ := os.Getwd()
	t.Logf("Working directory: %s", cwd)
	config := GetEnvConfiguration()

	configuration, configErr := NewConfiguration(config)
	require.Nil(t, configErr)

	apiClient := NewAPIClient(configuration)

	t.Run("Test ServerApiService SSHServersAccessDelete", func(t *testing.T) {

		t.Log("ServerApi_SSHServersAccessDelete_payload: <none>")
		resp, httpRes, err := apiClient.ServerApi.SSHServersAccessDelete(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ServerApiService SSHServersAccessIdGet", func(t *testing.T) {

		var id interface{}

		id = os.Getenv("ServerApi_SSHServersAccessIdGet_id")
		id, _ = convertParamInterface(id, "int32")
		t.Logf("ServerApi_SSHServersAccessIdGet_id: %v", id)

		t.Log("ServerApi_SSHServersAccessIdGet_payload: <none>")
		resp, httpRes, err := apiClient.ServerApi.SSHServersAccessIdGet(context.Background(), id.(int32)).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ServerApiService SSHServersAccessPost", func(t *testing.T) {

		t.Log("ServerApi_SSHServersAccessPost_payload: <none>")
		resp, httpRes, err := apiClient.ServerApi.SSHServersAccessPost(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ServerApiService SSHServersGet", func(t *testing.T) {

		t.Log("ServerApi_SSHServersGet_payload: <none>")
		resp, httpRes, err := apiClient.ServerApi.SSHServersGet(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ServerApiService SSHServersIdDelete", func(t *testing.T) {

		var id interface{}

		id = os.Getenv("ServerApi_SSHServersIdDelete_id")
		id, _ = convertParamInterface(id, "int32")
		t.Logf("ServerApi_SSHServersIdDelete_id: %v", id)

		t.Log("ServerApi_SSHServersIdDelete_payload: <none>")
		httpRes, err := apiClient.ServerApi.SSHServersIdDelete(context.Background(), id.(int32)).Execute()
		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ServerApiService SSHServersIdGet", func(t *testing.T) {

		var id interface{}

		id = os.Getenv("ServerApi_SSHServersIdGet_id")
		id, _ = convertParamInterface(id, "int32")
		t.Logf("ServerApi_SSHServersIdGet_id: %v", id)

		t.Log("ServerApi_SSHServersIdGet_payload: <none>")
		resp, httpRes, err := apiClient.ServerApi.SSHServersIdGet(context.Background(), id.(int32)).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ServerApiService SSHServersPost", func(t *testing.T) {

		t.Log("ServerApi_SSHServersPost_payload: <none>")
		resp, httpRes, err := apiClient.ServerApi.SSHServersPost(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ServerApiService SSHServersPut", func(t *testing.T) {

		t.Log("ServerApi_SSHServersPut_payload: <none>")
		resp, httpRes, err := apiClient.ServerApi.SSHServersPut(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
