/*
Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

Testing WorkflowApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package command

import (
	"context"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_command_WorkflowApiService(t *testing.T) {

	cwd, _ := os.Getwd()
	t.Logf("Working directory: %s", cwd)
	config := GetEnvConfiguration()

	configuration, configErr := NewConfiguration(config)
	require.Nil(t, configErr)

	apiClient := NewAPIClient(configuration)

	t.Run("Test WorkflowApiService WorkflowCertificatesApprovePost", func(t *testing.T) {

		t.Log("WorkflowApi_WorkflowCertificatesApprovePost_payload: <none>")
		resp, httpRes, err := apiClient.WorkflowApi.WorkflowCertificatesApprovePost(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test WorkflowApiService WorkflowCertificatesDeniedGet", func(t *testing.T) {

		t.Log("WorkflowApi_WorkflowCertificatesDeniedGet_payload: <none>")
		resp, httpRes, err := apiClient.WorkflowApi.WorkflowCertificatesDeniedGet(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test WorkflowApiService WorkflowCertificatesDenyPost", func(t *testing.T) {

		t.Log("WorkflowApi_WorkflowCertificatesDenyPost_payload: <none>")
		resp, httpRes, err := apiClient.WorkflowApi.WorkflowCertificatesDenyPost(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test WorkflowApiService WorkflowCertificatesExternalValidationGet", func(t *testing.T) {

		t.Log("WorkflowApi_WorkflowCertificatesExternalValidationGet_payload: <none>")
		resp, httpRes, err := apiClient.WorkflowApi.WorkflowCertificatesExternalValidationGet(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test WorkflowApiService WorkflowCertificatesIdGet", func(t *testing.T) {

		var id interface{}

		id = os.Getenv("WorkflowApi_WorkflowCertificatesIdGet_id")
		id, _ = convertParamInterface(id, "int32")
		t.Logf("WorkflowApi_WorkflowCertificatesIdGet_id: %v", id)

		t.Log("WorkflowApi_WorkflowCertificatesIdGet_payload: <none>")
		resp, httpRes, err := apiClient.WorkflowApi.WorkflowCertificatesIdGet(context.Background(), id.(int32)).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test WorkflowApiService WorkflowCertificatesPendingGet", func(t *testing.T) {

		t.Log("WorkflowApi_WorkflowCertificatesPendingGet_payload: <none>")
		resp, httpRes, err := apiClient.WorkflowApi.WorkflowCertificatesPendingGet(context.Background()).Execute()
		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

}
