/*

Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

<p>This page provides a utility through which the Keyfactor API endpoints can be called and results returned.                                                           It is intended to be used primarily for validation, testing and workflow development.                                                           It also serves secondarily as documentation for the API.</p>                                                          <p>If you would like to view documentation containing details on the Keyfactor API and endpoints,                                                           please refer to the Web API section of the Keyfactor Command documentation.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package command

import (
	"encoding/json"
)

// checks if the KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse{}

// KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse struct for KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse
type KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse struct {
	AgentId        *string        `json:"agentId,omitempty"`
	EnableDiscover *bool          `json:"enableDiscover,omitempty"`
	EnableMonitor  *bool          `json:"enableMonitor,omitempty"`
	Version        NullableString `json:"version,omitempty"`
	AllowsDiscover *bool          `json:"allowsDiscover,omitempty"`
	AllowsMonitor  *bool          `json:"allowsMonitor,omitempty"`
	ClientMachine  NullableString `json:"clientMachine,omitempty"`
}

// NewKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse instantiates a new KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse() *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse {
	this := KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse{}
	return &this
}

// NewKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponseWithDefaults instantiates a new KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponseWithDefaults() *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse {
	this := KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse{}
	return &this
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetAgentId() string {
	if o == nil || isNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetAgentIdOk() (*string, bool) {
	if o == nil || isNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) HasAgentId() bool {
	if o != nil && !isNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetAgentId(v string) {
	o.AgentId = &v
}

// GetEnableDiscover returns the EnableDiscover field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetEnableDiscover() bool {
	if o == nil || isNil(o.EnableDiscover) {
		var ret bool
		return ret
	}
	return *o.EnableDiscover
}

// GetEnableDiscoverOk returns a tuple with the EnableDiscover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetEnableDiscoverOk() (*bool, bool) {
	if o == nil || isNil(o.EnableDiscover) {
		return nil, false
	}
	return o.EnableDiscover, true
}

// HasEnableDiscover returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) HasEnableDiscover() bool {
	if o != nil && !isNil(o.EnableDiscover) {
		return true
	}

	return false
}

// SetEnableDiscover gets a reference to the given bool and assigns it to the EnableDiscover field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetEnableDiscover(v bool) {
	o.EnableDiscover = &v
}

// GetEnableMonitor returns the EnableMonitor field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetEnableMonitor() bool {
	if o == nil || isNil(o.EnableMonitor) {
		var ret bool
		return ret
	}
	return *o.EnableMonitor
}

// GetEnableMonitorOk returns a tuple with the EnableMonitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetEnableMonitorOk() (*bool, bool) {
	if o == nil || isNil(o.EnableMonitor) {
		return nil, false
	}
	return o.EnableMonitor, true
}

// HasEnableMonitor returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) HasEnableMonitor() bool {
	if o != nil && !isNil(o.EnableMonitor) {
		return true
	}

	return false
}

// SetEnableMonitor gets a reference to the given bool and assigns it to the EnableMonitor field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetEnableMonitor(v bool) {
	o.EnableMonitor = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetVersion() string {
	if o == nil || isNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetVersion(v string) {
	o.Version.Set(&v)
}

// SetVersionNil sets the value for Version to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) UnsetVersion() {
	o.Version.Unset()
}

// GetAllowsDiscover returns the AllowsDiscover field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetAllowsDiscover() bool {
	if o == nil || isNil(o.AllowsDiscover) {
		var ret bool
		return ret
	}
	return *o.AllowsDiscover
}

// GetAllowsDiscoverOk returns a tuple with the AllowsDiscover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetAllowsDiscoverOk() (*bool, bool) {
	if o == nil || isNil(o.AllowsDiscover) {
		return nil, false
	}
	return o.AllowsDiscover, true
}

// HasAllowsDiscover returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) HasAllowsDiscover() bool {
	if o != nil && !isNil(o.AllowsDiscover) {
		return true
	}

	return false
}

// SetAllowsDiscover gets a reference to the given bool and assigns it to the AllowsDiscover field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetAllowsDiscover(v bool) {
	o.AllowsDiscover = &v
}

// GetAllowsMonitor returns the AllowsMonitor field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetAllowsMonitor() bool {
	if o == nil || isNil(o.AllowsMonitor) {
		var ret bool
		return ret
	}
	return *o.AllowsMonitor
}

// GetAllowsMonitorOk returns a tuple with the AllowsMonitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetAllowsMonitorOk() (*bool, bool) {
	if o == nil || isNil(o.AllowsMonitor) {
		return nil, false
	}
	return o.AllowsMonitor, true
}

// HasAllowsMonitor returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) HasAllowsMonitor() bool {
	if o != nil && !isNil(o.AllowsMonitor) {
		return true
	}

	return false
}

// SetAllowsMonitor gets a reference to the given bool and assigns it to the AllowsMonitor field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetAllowsMonitor(v bool) {
	o.AllowsMonitor = &v
}

// GetClientMachine returns the ClientMachine field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetClientMachine() string {
	if o == nil || isNil(o.ClientMachine.Get()) {
		var ret string
		return ret
	}
	return *o.ClientMachine.Get()
}

// GetClientMachineOk returns a tuple with the ClientMachine field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) GetClientMachineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientMachine.Get(), o.ClientMachine.IsSet()
}

// HasClientMachine returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) HasClientMachine() bool {
	if o != nil && o.ClientMachine.IsSet() {
		return true
	}

	return false
}

// SetClientMachine gets a reference to the given NullableString and assigns it to the ClientMachine field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetClientMachine(v string) {
	o.ClientMachine.Set(&v)
}

// SetClientMachineNil sets the value for ClientMachine to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) SetClientMachineNil() {
	o.ClientMachine.Set(nil)
}

// UnsetClientMachine ensures that no value is present for ClientMachine, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) UnsetClientMachine() {
	o.ClientMachine.Unset()
}

func (o KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AgentId) {
		toSerialize["agentId"] = o.AgentId
	}
	if !isNil(o.EnableDiscover) {
		toSerialize["enableDiscover"] = o.EnableDiscover
	}
	if !isNil(o.EnableMonitor) {
		toSerialize["enableMonitor"] = o.EnableMonitor
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if !isNil(o.AllowsDiscover) {
		toSerialize["allowsDiscover"] = o.AllowsDiscover
	}
	if !isNil(o.AllowsMonitor) {
		toSerialize["allowsMonitor"] = o.AllowsMonitor
	}
	if o.ClientMachine.IsSet() {
		toSerialize["clientMachine"] = o.ClientMachine.Get()
	}
	return toSerialize, nil
}

type NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse struct {
	value *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse
	isSet bool
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) Get() *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse {
	return v.value
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) Set(val *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse(val *KeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) *NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse {
	return &NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse{value: val, isSet: true}
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorPoolsAgentPoolAgentGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
