/*

Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

<p>This page provides a utility through which the Keyfactor API endpoints can be called and results returned.                                                           It is intended to be used primarily for validation, testing and workflow development.                                                           It also serves secondarily as documentation for the API.</p>                                                          <p>If you would like to view documentation containing details on the Keyfactor API and endpoints,                                                           please refer to the Web API section of the Keyfactor Command documentation.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package command

import (
	"encoding/json"
)

// checks if the KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse{}

// KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse struct for KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse
type KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse struct {
	InputParameters map[string]KeyfactorWebKeyfactorApiModelsWorkflowsParameterDefinitionResponse `json:"inputParameters,omitempty"`
}

// NewKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse instantiates a new KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse() *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse {
	this := KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse{}
	return &this
}

// NewKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponseWithDefaults instantiates a new KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponseWithDefaults() *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse {
	this := KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse{}
	return &this
}

// GetInputParameters returns the InputParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) GetInputParameters() map[string]KeyfactorWebKeyfactorApiModelsWorkflowsParameterDefinitionResponse {
	if o == nil {
		var ret map[string]KeyfactorWebKeyfactorApiModelsWorkflowsParameterDefinitionResponse
		return ret
	}
	return o.InputParameters
}

// GetInputParametersOk returns a tuple with the InputParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) GetInputParametersOk() (*map[string]KeyfactorWebKeyfactorApiModelsWorkflowsParameterDefinitionResponse, bool) {
	if o == nil || isNil(o.InputParameters) {
		return nil, false
	}
	return &o.InputParameters, true
}

// HasInputParameters returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) HasInputParameters() bool {
	if o != nil && isNil(o.InputParameters) {
		return true
	}

	return false
}

// SetInputParameters gets a reference to the given map[string]KeyfactorWebKeyfactorApiModelsWorkflowsParameterDefinitionResponse and assigns it to the InputParameters field.
func (o *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) SetInputParameters(v map[string]KeyfactorWebKeyfactorApiModelsWorkflowsParameterDefinitionResponse) {
	o.InputParameters = v
}

func (o KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.InputParameters != nil {
		toSerialize["inputParameters"] = o.InputParameters
	}
	return toSerialize, nil
}

type NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse struct {
	value *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse
	isSet bool
}

func (v NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) Get() *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse {
	return v.value
}

func (v *NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) Set(val *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse(val *KeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) *NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse {
	return &NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse{value: val, isSet: true}
}

func (v NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyfactorWebKeyfactorApiModelsWorkflowsSignalDefinitionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
