/*

Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

<p>This page provides a utility through which the Keyfactor API endpoints can be called and results returned.                                                           It is intended to be used primarily for validation, testing and workflow development.                                                           It also serves secondarily as documentation for the API.</p>                                                          <p>If you would like to view documentation containing details on the Keyfactor API and endpoints,                                                           please refer to the Web API section of the Keyfactor Command documentation.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package command

import (
	"encoding/json"
	"time"
)

// checks if the KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse{}

// KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse struct for KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse
type KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse struct {
	JobTypeName           NullableString                                                   `json:"jobTypeName,omitempty"`
	Schedule              *KeyfactorCommonSchedulingKeyfactorSchedule                      `json:"schedule,omitempty"`
	JobFields             []KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobFieldResponse `json:"jobFields,omitempty"`
	RequestTimestamp      *time.Time                                                       `json:"requestTimestamp,omitempty"`
	OrchestratorJobPairs  []ModelsOrchestratorJobsBulkOrchestratorJobPair                  `json:"orchestratorJobPairs,omitempty"`
	FailedOrchestratorIds []string                                                         `json:"failedOrchestratorIds,omitempty"`
}

// NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse instantiates a new KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse() *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse {
	this := KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse{}
	return &this
}

// NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponseWithDefaults instantiates a new KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponseWithDefaults() *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse {
	this := KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse{}
	return &this
}

// GetJobTypeName returns the JobTypeName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetJobTypeName() string {
	if o == nil || isNil(o.JobTypeName.Get()) {
		var ret string
		return ret
	}
	return *o.JobTypeName.Get()
}

// GetJobTypeNameOk returns a tuple with the JobTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetJobTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobTypeName.Get(), o.JobTypeName.IsSet()
}

// HasJobTypeName returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) HasJobTypeName() bool {
	if o != nil && o.JobTypeName.IsSet() {
		return true
	}

	return false
}

// SetJobTypeName gets a reference to the given NullableString and assigns it to the JobTypeName field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) SetJobTypeName(v string) {
	o.JobTypeName.Set(&v)
}

// SetJobTypeNameNil sets the value for JobTypeName to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) SetJobTypeNameNil() {
	o.JobTypeName.Set(nil)
}

// UnsetJobTypeName ensures that no value is present for JobTypeName, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) UnsetJobTypeName() {
	o.JobTypeName.Unset()
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetSchedule() KeyfactorCommonSchedulingKeyfactorSchedule {
	if o == nil || isNil(o.Schedule) {
		var ret KeyfactorCommonSchedulingKeyfactorSchedule
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetScheduleOk() (*KeyfactorCommonSchedulingKeyfactorSchedule, bool) {
	if o == nil || isNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) HasSchedule() bool {
	if o != nil && !isNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given KeyfactorCommonSchedulingKeyfactorSchedule and assigns it to the Schedule field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) SetSchedule(v KeyfactorCommonSchedulingKeyfactorSchedule) {
	o.Schedule = &v
}

// GetJobFields returns the JobFields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetJobFields() []KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobFieldResponse {
	if o == nil {
		var ret []KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobFieldResponse
		return ret
	}
	return o.JobFields
}

// GetJobFieldsOk returns a tuple with the JobFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetJobFieldsOk() ([]KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobFieldResponse, bool) {
	if o == nil || isNil(o.JobFields) {
		return nil, false
	}
	return o.JobFields, true
}

// HasJobFields returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) HasJobFields() bool {
	if o != nil && isNil(o.JobFields) {
		return true
	}

	return false
}

// SetJobFields gets a reference to the given []KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobFieldResponse and assigns it to the JobFields field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) SetJobFields(v []KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobFieldResponse) {
	o.JobFields = v
}

// GetRequestTimestamp returns the RequestTimestamp field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetRequestTimestamp() time.Time {
	if o == nil || isNil(o.RequestTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.RequestTimestamp
}

// GetRequestTimestampOk returns a tuple with the RequestTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetRequestTimestampOk() (*time.Time, bool) {
	if o == nil || isNil(o.RequestTimestamp) {
		return nil, false
	}
	return o.RequestTimestamp, true
}

// HasRequestTimestamp returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) HasRequestTimestamp() bool {
	if o != nil && !isNil(o.RequestTimestamp) {
		return true
	}

	return false
}

// SetRequestTimestamp gets a reference to the given time.Time and assigns it to the RequestTimestamp field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) SetRequestTimestamp(v time.Time) {
	o.RequestTimestamp = &v
}

// GetOrchestratorJobPairs returns the OrchestratorJobPairs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetOrchestratorJobPairs() []ModelsOrchestratorJobsBulkOrchestratorJobPair {
	if o == nil {
		var ret []ModelsOrchestratorJobsBulkOrchestratorJobPair
		return ret
	}
	return o.OrchestratorJobPairs
}

// GetOrchestratorJobPairsOk returns a tuple with the OrchestratorJobPairs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetOrchestratorJobPairsOk() ([]ModelsOrchestratorJobsBulkOrchestratorJobPair, bool) {
	if o == nil || isNil(o.OrchestratorJobPairs) {
		return nil, false
	}
	return o.OrchestratorJobPairs, true
}

// HasOrchestratorJobPairs returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) HasOrchestratorJobPairs() bool {
	if o != nil && isNil(o.OrchestratorJobPairs) {
		return true
	}

	return false
}

// SetOrchestratorJobPairs gets a reference to the given []ModelsOrchestratorJobsBulkOrchestratorJobPair and assigns it to the OrchestratorJobPairs field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) SetOrchestratorJobPairs(v []ModelsOrchestratorJobsBulkOrchestratorJobPair) {
	o.OrchestratorJobPairs = v
}

// GetFailedOrchestratorIds returns the FailedOrchestratorIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetFailedOrchestratorIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FailedOrchestratorIds
}

// GetFailedOrchestratorIdsOk returns a tuple with the FailedOrchestratorIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) GetFailedOrchestratorIdsOk() ([]string, bool) {
	if o == nil || isNil(o.FailedOrchestratorIds) {
		return nil, false
	}
	return o.FailedOrchestratorIds, true
}

// HasFailedOrchestratorIds returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) HasFailedOrchestratorIds() bool {
	if o != nil && isNil(o.FailedOrchestratorIds) {
		return true
	}

	return false
}

// SetFailedOrchestratorIds gets a reference to the given []string and assigns it to the FailedOrchestratorIds field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) SetFailedOrchestratorIds(v []string) {
	o.FailedOrchestratorIds = v
}

func (o KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.JobTypeName.IsSet() {
		toSerialize["jobTypeName"] = o.JobTypeName.Get()
	}
	if !isNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if o.JobFields != nil {
		toSerialize["jobFields"] = o.JobFields
	}
	if !isNil(o.RequestTimestamp) {
		toSerialize["requestTimestamp"] = o.RequestTimestamp
	}
	if o.OrchestratorJobPairs != nil {
		toSerialize["orchestratorJobPairs"] = o.OrchestratorJobPairs
	}
	if o.FailedOrchestratorIds != nil {
		toSerialize["failedOrchestratorIds"] = o.FailedOrchestratorIds
	}
	return toSerialize, nil
}

type NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse struct {
	value *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse
	isSet bool
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) Get() *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse {
	return v.value
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) Set(val *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse(val *KeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse {
	return &NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse{value: val, isSet: true}
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsBulkJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
