/*

Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

<p>This page provides a utility through which the Keyfactor API endpoints can be called and results returned.                                                           It is intended to be used primarily for validation, testing and workflow development.                                                           It also serves secondarily as documentation for the API.</p>                                                          <p>If you would like to view documentation containing details on the Keyfactor API and endpoints,                                                           please refer to the Web API section of the Keyfactor Command documentation.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package command

import (
	"encoding/json"
)

// checks if the KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse{}

// KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse struct for KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse
type KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse struct {
	Name         NullableString `json:"name,omitempty"`
	Type         *int32         `json:"type,omitempty"`
	DefaultValue NullableString `json:"defaultValue,omitempty"`
	Required     *bool          `json:"required,omitempty"`
}

// NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse instantiates a new KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse() *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse {
	this := KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse{}
	return &this
}

// NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponseWithDefaults instantiates a new KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponseWithDefaults() *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse {
	this := KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetName() string {
	if o == nil || isNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) UnsetName() {
	o.Name.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetType() int32 {
	if o == nil || isNil(o.Type) {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetTypeOk() (*int32, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) SetType(v int32) {
	o.Type = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetDefaultValue() string {
	if o == nil || isNil(o.DefaultValue.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultValue.Get()
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetDefaultValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultValue.Get(), o.DefaultValue.IsSet()
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) HasDefaultValue() bool {
	if o != nil && o.DefaultValue.IsSet() {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given NullableString and assigns it to the DefaultValue field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) SetDefaultValue(v string) {
	o.DefaultValue.Set(&v)
}

// SetDefaultValueNil sets the value for DefaultValue to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) SetDefaultValueNil() {
	o.DefaultValue.Set(nil)
}

// UnsetDefaultValue ensures that no value is present for DefaultValue, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) UnsetDefaultValue() {
	o.DefaultValue.Unset()
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetRequired() bool {
	if o == nil || isNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) GetRequiredOk() (*bool, bool) {
	if o == nil || isNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) HasRequired() bool {
	if o != nil && !isNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) SetRequired(v bool) {
	o.Required = &v
}

func (o KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.DefaultValue.IsSet() {
		toSerialize["defaultValue"] = o.DefaultValue.Get()
	}
	if !isNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	return toSerialize, nil
}

type NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse struct {
	value *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse
	isSet bool
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) Get() *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse {
	return v.value
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) Set(val *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse(val *KeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse {
	return &NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse{value: val, isSet: true}
}

func (v NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyfactorWebKeyfactorApiModelsOrchestratorJobsJobTypeFieldResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
