/*

Copyright 2023 Keyfactor
Licensed under the Apache License, Version 2.0 (the License); you may
not use this file except in compliance with the License.  You may obtain a
copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
required by applicable law or agreed to in writing, software distributed
under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License.

Keyfactor API Reference and Utility

<p>This page provides a utility through which the Keyfactor API endpoints can be called and results returned.                                                           It is intended to be used primarily for validation, testing and workflow development.                                                           It also serves secondarily as documentation for the API.</p>                                                          <p>If you would like to view documentation containing details on the Keyfactor API and endpoints,                                                           please refer to the Web API section of the Keyfactor Command documentation.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package command

import (
	"encoding/json"
)

// checks if the KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse{}

// KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse struct for KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse
type KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse struct {
	Id                     *int32                                                                    `json:"id,omitempty"`
	DisplayName            NullableString                                                            `json:"displayName,omitempty"`
	Subject                NullableString                                                            `json:"subject,omitempty"`
	Message                NullableString                                                            `json:"message,omitempty"`
	Recipient              NullableString                                                            `json:"recipient,omitempty"`
	RotationWarningDays    *int32                                                                    `json:"rotationWarningDays,omitempty"`
	RegisteredEventHandler *KeyfactorWebKeyfactorApiModelsEventHandlerRegisteredEventHandlerResponse `json:"registeredEventHandler,omitempty"`
	EventHandlerParameters []KeyfactorWebKeyfactorApiModelsEventHandlerEventHandlerParameterResponse `json:"eventHandlerParameters,omitempty"`
}

// NewKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse instantiates a new KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse() *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse {
	this := KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse{}
	return &this
}

// NewKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponseWithDefaults instantiates a new KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponseWithDefaults() *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse {
	this := KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetId(v int32) {
	o.Id = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}

// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetSubject returns the Subject field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetSubject() string {
	if o == nil || isNil(o.Subject.Get()) {
		var ret string
		return ret
	}
	return *o.Subject.Get()
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subject.Get(), o.Subject.IsSet()
}

// HasSubject returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasSubject() bool {
	if o != nil && o.Subject.IsSet() {
		return true
	}

	return false
}

// SetSubject gets a reference to the given NullableString and assigns it to the Subject field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetSubject(v string) {
	o.Subject.Set(&v)
}

// SetSubjectNil sets the value for Subject to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetSubjectNil() {
	o.Subject.Set(nil)
}

// UnsetSubject ensures that no value is present for Subject, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) UnsetSubject() {
	o.Subject.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetMessage() string {
	if o == nil || isNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetMessage(v string) {
	o.Message.Set(&v)
}

// SetMessageNil sets the value for Message to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) UnsetMessage() {
	o.Message.Unset()
}

// GetRecipient returns the Recipient field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetRecipient() string {
	if o == nil || isNil(o.Recipient.Get()) {
		var ret string
		return ret
	}
	return *o.Recipient.Get()
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recipient.Get(), o.Recipient.IsSet()
}

// HasRecipient returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasRecipient() bool {
	if o != nil && o.Recipient.IsSet() {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given NullableString and assigns it to the Recipient field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetRecipient(v string) {
	o.Recipient.Set(&v)
}

// SetRecipientNil sets the value for Recipient to be an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetRecipientNil() {
	o.Recipient.Set(nil)
}

// UnsetRecipient ensures that no value is present for Recipient, not even an explicit nil
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) UnsetRecipient() {
	o.Recipient.Unset()
}

// GetRotationWarningDays returns the RotationWarningDays field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetRotationWarningDays() int32 {
	if o == nil || isNil(o.RotationWarningDays) {
		var ret int32
		return ret
	}
	return *o.RotationWarningDays
}

// GetRotationWarningDaysOk returns a tuple with the RotationWarningDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetRotationWarningDaysOk() (*int32, bool) {
	if o == nil || isNil(o.RotationWarningDays) {
		return nil, false
	}
	return o.RotationWarningDays, true
}

// HasRotationWarningDays returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasRotationWarningDays() bool {
	if o != nil && !isNil(o.RotationWarningDays) {
		return true
	}

	return false
}

// SetRotationWarningDays gets a reference to the given int32 and assigns it to the RotationWarningDays field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetRotationWarningDays(v int32) {
	o.RotationWarningDays = &v
}

// GetRegisteredEventHandler returns the RegisteredEventHandler field value if set, zero value otherwise.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetRegisteredEventHandler() KeyfactorWebKeyfactorApiModelsEventHandlerRegisteredEventHandlerResponse {
	if o == nil || isNil(o.RegisteredEventHandler) {
		var ret KeyfactorWebKeyfactorApiModelsEventHandlerRegisteredEventHandlerResponse
		return ret
	}
	return *o.RegisteredEventHandler
}

// GetRegisteredEventHandlerOk returns a tuple with the RegisteredEventHandler field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetRegisteredEventHandlerOk() (*KeyfactorWebKeyfactorApiModelsEventHandlerRegisteredEventHandlerResponse, bool) {
	if o == nil || isNil(o.RegisteredEventHandler) {
		return nil, false
	}
	return o.RegisteredEventHandler, true
}

// HasRegisteredEventHandler returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasRegisteredEventHandler() bool {
	if o != nil && !isNil(o.RegisteredEventHandler) {
		return true
	}

	return false
}

// SetRegisteredEventHandler gets a reference to the given KeyfactorWebKeyfactorApiModelsEventHandlerRegisteredEventHandlerResponse and assigns it to the RegisteredEventHandler field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetRegisteredEventHandler(v KeyfactorWebKeyfactorApiModelsEventHandlerRegisteredEventHandlerResponse) {
	o.RegisteredEventHandler = &v
}

// GetEventHandlerParameters returns the EventHandlerParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetEventHandlerParameters() []KeyfactorWebKeyfactorApiModelsEventHandlerEventHandlerParameterResponse {
	if o == nil {
		var ret []KeyfactorWebKeyfactorApiModelsEventHandlerEventHandlerParameterResponse
		return ret
	}
	return o.EventHandlerParameters
}

// GetEventHandlerParametersOk returns a tuple with the EventHandlerParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) GetEventHandlerParametersOk() ([]KeyfactorWebKeyfactorApiModelsEventHandlerEventHandlerParameterResponse, bool) {
	if o == nil || isNil(o.EventHandlerParameters) {
		return nil, false
	}
	return o.EventHandlerParameters, true
}

// HasEventHandlerParameters returns a boolean if a field has been set.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) HasEventHandlerParameters() bool {
	if o != nil && isNil(o.EventHandlerParameters) {
		return true
	}

	return false
}

// SetEventHandlerParameters gets a reference to the given []KeyfactorWebKeyfactorApiModelsEventHandlerEventHandlerParameterResponse and assigns it to the EventHandlerParameters field.
func (o *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) SetEventHandlerParameters(v []KeyfactorWebKeyfactorApiModelsEventHandlerEventHandlerParameterResponse) {
	o.EventHandlerParameters = v
}

func (o KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.Subject.IsSet() {
		toSerialize["subject"] = o.Subject.Get()
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.Recipient.IsSet() {
		toSerialize["recipient"] = o.Recipient.Get()
	}
	if !isNil(o.RotationWarningDays) {
		toSerialize["rotationWarningDays"] = o.RotationWarningDays
	}
	if !isNil(o.RegisteredEventHandler) {
		toSerialize["registeredEventHandler"] = o.RegisteredEventHandler
	}
	if o.EventHandlerParameters != nil {
		toSerialize["eventHandlerParameters"] = o.EventHandlerParameters
	}
	return toSerialize, nil
}

type NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse struct {
	value *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse
	isSet bool
}

func (v NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) Get() *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse {
	return v.value
}

func (v *NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) Set(val *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse(val *KeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) *NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse {
	return &NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse{value: val, isSet: true}
}

func (v NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyfactorWebKeyfactorApiModelsAlertsKeyRotationKeyRotationAlertDefinitionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
