name: GoLang Test
on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        environment: [KFC9, KFC10, KFC11]
        go-version: [ '1.18', '1.19', '1.20']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo $ENV_FILE | base64 --decode > .env && source .env && go test -v ./api...



